import type { OddsQuestion } from "../types";

export const oddsQuestions: OddsQuestion[] = [
  {
    id: "odds-001",
    category: "odds",
    difficulty: "기초",
    title: "Turn Flush Draw",
    prompt: "턴에서 하트 플러시 드로우만 남아 있어, 리버 한 장으로 하트가 떨어질 때만 완성됩니다.",
    explanation: "턴에서 9아웃은 대략 9 x 2 = 18% 규칙을 적용하면 충분합니다. 엄밀히는 조금 더 높지만 실전 감각상 약 19%로 기억하면 됩니다.",
    pitfall: "플랍과 턴의 확률을 같은 숫자로 기억해 과대평가하는 실수",
    tags: ["아웃 계산", "턴 확률"],
    holeCards: ["Ah", "Jh"],
    board: ["Kh", "9h", "2c", "7s"],
    outsSpec: {
      components: ["flushDraw"],
    },
    pot: "24bb",
    villainBet: "12bb",
    actionBefore: "Turn: 9 Outs Flush Draw",
    mathFocus: "9 Outs / Turn to River",
    options: [
      {
        value: "19",
        label: "약 19%",
      },
      {
        value: "28",
        label: "약 28%",
      },
      {
        value: "36",
        label: "약 36%",
      },
    ],
    correct: "19",
  },
  {
    id: "odds-002",
    category: "odds",
    difficulty: "기초",
    title: "Flop Open-Ended",
    prompt: "플랍에서 98은 T72 보드에서, 6이나 J가 오면 스트레이트가 완성됩니다.",
    explanation: "플랍에서 8아웃은 대략 8 x 4 = 32% 정도입니다. 빠르게 판단할 땐 31~32%로 외워두면 충분합니다.",
    pitfall: "오픈엔디드를 거트샷 수준으로 과소평가하는 실수",
    tags: ["아웃 계산", "플랍 확률"],
    holeCards: ["9s", "8s"],
    board: ["Td", "7c", "2h"],
    outsSpec: {
      components: ["straightDraw"],
    },
    pot: "9bb",
    villainBet: "4bb",
    actionBefore: "Flop: Open-Ended Straight Draw",
    mathFocus: "8 Outs / Flop to River",
    options: [
      {
        value: "17",
        label: "약 17%",
      },
      {
        value: "31",
        label: "약 31%",
      },
      {
        value: "46",
        label: "약 46%",
      },
    ],
    correct: "31",
  },
  {
    id: "odds-003",
    category: "odds",
    difficulty: "기초",
    title: "Turn Gutshot",
    prompt: "턴에서 Q9는 KJ 보드에 T 한 장만 들어오면 스트레이트가 되는 거트샷입니다.",
    explanation: "4아웃이 턴에서 리버 한 장 남았으면 대략 8~9% 정도입니다. 큰 베팅을 상대할 때 희망콜을 줄이는 데 중요한 숫자입니다.",
    pitfall: "거트샷을 너무 자주 따라가며 칩을 흘리는 실수",
    tags: ["아웃 계산", "턴 확률"],
    holeCards: ["Qh", "9s"],
    board: ["Kd", "Jc", "5h", "2d"],
    outsSpec: {
      components: ["straightDraw"],
    },
    pot: "20bb",
    villainBet: "14bb",
    actionBefore: "Turn: Gutshot Straight Draw (4 Outs)",
    mathFocus: "4 Outs / Turn to River",
    options: [
      {
        value: "9",
        label: "약 9%",
      },
      {
        value: "18",
        label: "약 18%",
      },
      {
        value: "26",
        label: "약 26%",
      },
    ],
    correct: "9",
  },
  {
    id: "odds-004",
    category: "odds",
    difficulty: "실전",
    title: "Half Pot: Required Equity",
    prompt: "기존 팟 40bb에 상대가 20bb를 베팅했고, 지금은 콜에 필요한 최소 승률만 계산하면 됩니다.",
    explanation: "하프 팟 베팅엔 약 25% 정도의 승률이 필요합니다. 이 기준을 머릿속에 넣어두면 드로우 콜 판단이 빨라집니다.",
    pitfall: "포트 오즈 없이 감으로만 콜하는 실수",
    tags: ["포트 오즈", "필요 승률"],
    pot: "60bb",
    villainBet: "20bb",
    actionBefore: "기존 팟 40bb에 상대가 20bb(하프 팟) 베팅해 현재 팟이 60bb인 상황",
    mathFocus: "Half Pot Bet",
    options: [
      {
        value: "25",
        label: "약 25%",
      },
      {
        value: "33",
        label: "약 33%",
      },
      {
        value: "40",
        label: "약 40%",
      },
    ],
    correct: "25",
  },
  {
    id: "odds-005",
    category: "odds",
    difficulty: "응용",
    title: "Combo Draw 15 Outs",
    prompt: "플랍에서 AhJh가 QhTh 보드를 만나 플러시와 스트레이트 쪽 개선 카드가 동시에 열려 있습니다.",
    explanation: "플랍에서 15아웃은 대략 15 x 4 = 60%에 가깝지만 중복과 보정 때문에 실전 감각상 54% 안팎으로 잡으면 됩니다.",
    pitfall: "강한 콤보 드로우의 실제 힘을 몰라 너무 쉽게 포기하는 실수",
    tags: ["아웃 계산", "콤보 드로우"],
    holeCards: ["Ah", "Jh"],
    board: ["Qh", "Th", "2c"],
    outsSpec: {
      components: ["flushDraw", "straightDraw", "overcardPair"],
    },
    pot: "18bb",
    villainBet: "9bb",
    actionBefore: "Flop: 15 Outs Combo Draw",
    mathFocus: "15 Outs / Flop to River",
    options: [
      {
        value: "29",
        label: "약 29%",
      },
      {
        value: "54",
        label: "약 54%",
      },
      {
        value: "71",
        label: "약 71%",
      },
    ],
    correct: "54",
  },
  {
    id: "odds-006",
    category: "odds",
    difficulty: "실전",
    title: "15 into 70",
    prompt: "현재 팟은 70bb이고 콜 금액은 15bb라, 콜 뒤 최종 팟 기준으로 필요한 승률을 빠르게 계산해야 하는 상황입니다.",
    explanation: "15를 콜하면 총 85를 놓고 싸우게 되므로 필요한 승률은 약 18%입니다. 애매한 숫자도 한 번씩 익혀 두면 테이블에서 계산이 덜 흔들립니다.",
    pitfall: "콜 금액과 최종 팟 크기를 구분하지 못하는 실수",
    tags: ["포트 오즈", "필요 승률"],
    pot: "70bb",
    villainBet: "15bb",
    actionBefore: "내가 15를 콜하면 총 팟이 85가 되는 상황",
    mathFocus: "15 call to win 85",
    options: [
      {
        value: "18",
        label: "약 18%",
      },
      {
        value: "22",
        label: "약 22%",
      },
      {
        value: "33",
        label: "약 33%",
      },
    ],
    correct: "18",
  },
  {
    id: "odds-007",
    category: "odds",
    difficulty: "기초",
    title: "풀팟 베팅의 필요 승률",
    prompt: "기존 팟 30bb에 상대가 30bb를 베팅해, 풀팟 콜에 필요한 최소 승률을 빠르게 떠올려야 하는 상황입니다.",
    explanation: "팟 사이즈 베팅에는 약 33%의 승률이 필요합니다. 하프 팟(25%)과 함께 가장 자주 나오는 기준이므로 몸에 배게 외우면 좋습니다.",
    pitfall: "풀팟 베팅과 하프 팟 베팅의 필요 승률을 혼동하는 실수",
    tags: ["포트 오즈", "필요 승률"],
    pot: "60bb",
    villainBet: "30bb",
    actionBefore: "기존 팟 30bb에 상대가 30bb(풀팟) 베팅해 현재 팟이 60bb인 상황",
    mathFocus: "상대가 풀팟 베팅",
    options: [
      {
        value: "25",
        label: "약 25%",
      },
      {
        value: "33",
        label: "약 33%",
      },
      {
        value: "50",
        label: "약 50%",
      },
    ],
    correct: "33",
  },
  {
    id: "odds-008",
    category: "odds",
    difficulty: "기초",
    title: "Flop Flush Draw 9 Outs",
    prompt: "플랍에서 A-high 클럽 플러시 드로우를 만들었고, 턴과 리버 두 장을 모두 볼 수 있습니다.",
    explanation: "플랍에서 9아웃은 빠른 계산으로 9 x 4 = 36% 정도로 잡으면 됩니다. 정밀하게는 약 35%라서 실전에서는 35% 전후로 기억해 두면 충분합니다.",
    pitfall: "플랍 확률과 턴 확률을 같은 숫자로 외워 과소평가하는 실수",
    tags: ["아웃 계산", "플랍 확률"],
    holeCards: ["Ac", "Jc"],
    board: ["Qc", "7c", "2d"],
    outsSpec: {
      components: ["flushDraw"],
    },
    pot: "15bb",
    villainBet: "10bb",
    actionBefore: "Flop: 9 Outs Flush Draw",
    mathFocus: "9 Outs / Flop to River",
    options: [
      {
        value: "19",
        label: "약 19%",
      },
      {
        value: "35",
        label: "약 35%",
      },
      {
        value: "52",
        label: "약 52%",
      },
    ],
    correct: "35",
  },
  {
    id: "odds-009",
    category: "odds",
    difficulty: "기초",
    title: "Pocket Pair: 2 Outs",
    prompt: "플랍에서 99는 A72 보드에서, 남은 9를 맞혀 셋으로 좋아지는 경우만 생각하면 됩니다.",
    explanation: "플랍에서 2아웃으로 턴과 리버를 모두 본다면 약 8% 정도입니다. 세트 가능성만 보고 큰 베팅을 따라가기엔 생각보다 낮은 숫자입니다.",
    pitfall: "포켓페어가 셋으로 좋아질 확률을 실제보다 훨씬 높게 기억하는 실수",
    tags: ["아웃 계산", "플랍 확률"],
    holeCards: ["9c", "9d"],
    board: ["As", "7h", "2c"],
    outsSpec: {
      components: ["pocketPairSet"],
    },
    pot: "12bb",
    villainBet: "6bb",
    actionBefore: "Flop: 언더페어가 셋으로 좋아질 2아웃",
    mathFocus: "2 Outs / Flop to River",
    options: [
      {
        value: "8",
        label: "약 8%",
      },
      {
        value: "17",
        label: "약 17%",
      },
      {
        value: "31",
        label: "약 31%",
      },
    ],
    correct: "8",
  },
  {
    id: "odds-010",
    category: "odds",
    difficulty: "기초",
    title: "Turn Set Saver",
    prompt: "턴에서 88은 KJ42 보드에서, 리버 한 장으로 남은 8을 맞힐 때만 셋이 됩니다.",
    explanation: "턴에서 2아웃이면 리버 한 장만 남아 있어 확률은 약 4%입니다. 턴 이후엔 플랍 때처럼 넉넉한 확률을 기대하면 안 됩니다.",
    pitfall: "턴과 플랍의 세트 확률을 같은 수준으로 착각하는 실수",
    tags: ["아웃 계산", "턴 확률"],
    holeCards: ["8s", "8d"],
    board: ["Kc", "Jh", "4s", "2d"],
    outsSpec: {
      components: ["pocketPairSet"],
    },
    pot: "18bb",
    villainBet: "10bb",
    actionBefore: "Turn: 포켓페어가 셋으로 좋아질 2아웃",
    mathFocus: "2 Outs / Turn to River",
    options: [
      {
        value: "4",
        label: "약 4%",
      },
      {
        value: "9",
        label: "약 9%",
      },
      {
        value: "18",
        label: "약 18%",
      },
    ],
    correct: "4",
  },
  {
    id: "odds-011",
    category: "odds",
    difficulty: "기초",
    title: "Two Overcards",
    prompt: "플랍에서 AKo는 Q83 보드에서, A나 K가 떨어질 때만 원페어로 개선됩니다.",
    explanation: "두 오버카드는 보통 6아웃으로 계산해 플랍에서 리버까지 약 24% 정도입니다. 그냥 막연히 '에이스킹이니까 맞겠지' 하고 생각하면 과대평가가 됩니다.",
    pitfall: "오버카드 두 장의 실제 개선 확률을 너무 높게 보는 실수",
    tags: ["아웃 계산", "플랍 확률"],
    holeCards: ["Ah", "Kc"],
    board: ["Qd", "8s", "3h"],
    outsSpec: {
      components: ["overcardPair"],
    },
    pot: "10bb",
    villainBet: "5bb",
    actionBefore: "Flop: 두 오버카드 = 6아웃",
    mathFocus: "6 Outs / Flop to River",
    options: [
      {
        value: "13",
        label: "약 13%",
      },
      {
        value: "24",
        label: "약 24%",
      },
      {
        value: "35",
        label: "약 35%",
      },
    ],
    correct: "24",
  },
  {
    id: "odds-012",
    category: "odds",
    difficulty: "기초",
    title: "Turn Open-Ended",
    prompt: "턴에서 98은 T72K 보드에서, 6이나 J가 리버에 오면 스트레이트가 완성됩니다.",
    explanation: "턴 8아웃은 대략 8 x 2 규칙으로 16~17% 정도로 보면 됩니다. 플랍의 31%와 혼동하면 너무 넓게 따라가게 됩니다.",
    pitfall: "턴 오픈엔디드 확률을 플랍 수치와 혼동해 과대평가하는 실수",
    tags: ["아웃 계산", "턴 확률"],
    holeCards: ["9s", "8s"],
    board: ["Td", "7c", "2h", "Kc"],
    outsSpec: {
      components: ["straightDraw"],
    },
    pot: "22bb",
    villainBet: "12bb",
    actionBefore: "Turn: Open-Ended Straight Draw",
    mathFocus: "8 Outs / Turn to River",
    options: [
      {
        value: "9",
        label: "약 9%",
      },
      {
        value: "17",
        label: "약 17%",
      },
      {
        value: "26",
        label: "약 26%",
      },
    ],
    correct: "17",
  },
  {
    id: "odds-013",
    category: "odds",
    difficulty: "실전",
    title: "12 Outs on the Flop",
    prompt: "플랍에서 AhJh는 KhTh4d 보드에서, 하트와 Q가 모두 강한 개선 카드로 작용합니다.",
    explanation: "12아웃은 플랍에서 리버까지 약 45%입니다. 절반에 가까운 수치라 강한 드로우가 왜 공격적으로 플레이되는지 이해하는 데 중요합니다.",
    pitfall: "강한 드로우 12아웃의 실제 에퀴티를 과소평가하는 실수",
    tags: ["아웃 계산", "플랍 확률"],
    holeCards: ["Ah", "Jh"],
    board: ["Kh", "Th", "4d"],
    outsSpec: {
      components: ["flushDraw", "straightDraw"],
    },
    pot: "18bb",
    villainBet: "9bb",
    actionBefore: "Flop: Flush Draw + Gutshot (12 Outs)",
    mathFocus: "12 Outs / Flop to River",
    options: [
      {
        value: "31",
        label: "약 31%",
      },
      {
        value: "45",
        label: "약 45%",
      },
      {
        value: "59",
        label: "약 59%",
      },
    ],
    correct: "45",
  },
  {
    id: "odds-014",
    category: "odds",
    difficulty: "응용",
    title: "Turn Combo Draw 15 Outs",
    prompt: "턴에서 9h8h는 Th7h2cKs 보드에서, 하트와 6/J 쪽 카드들이 함께 개선 후보입니다.",
    explanation: "턴 15아웃은 약 33%입니다. 플랍에서의 54%와는 전혀 다른 숫자라, 한 장만 남았다는 점을 항상 분리해서 생각해야 합니다.",
    pitfall: "턴 콤보 드로우를 플랍 수준의 고에퀴티로 착각하는 실수",
    tags: ["아웃 계산", "턴 확률"],
    holeCards: ["9h", "8h"],
    board: ["Th", "7h", "2c", "Ks"],
    outsSpec: {
      components: ["flushDraw", "straightDraw"],
    },
    pot: "30bb",
    villainBet: "20bb",
    actionBefore: "Turn: Flush Draw + OESD (15 Outs)",
    mathFocus: "15 Outs / Turn to River",
    options: [
      {
        value: "19",
        label: "약 19%",
      },
      {
        value: "33",
        label: "약 33%",
      },
      {
        value: "54",
        label: "약 54%",
      },
    ],
    correct: "33",
  },
  {
    id: "odds-015",
    category: "odds",
    difficulty: "기초",
    title: "Quarter Pot: Required Equity",
    prompt: "기존 팟 40bb에 상대가 10bb를 베팅했고, 작은 사이즈 앞에서 콜에 필요한 승률을 계산해야 합니다.",
    explanation: "1/4 팟 베팅엔 약 17%의 승률만 있으면 됩니다. 가격이 좋기 때문에 약한 드로우도 종종 계속 갈 수 있는 이유가 여기 있습니다.",
    pitfall: "작은 베팅의 좋은 가격을 무시하고 필요 승률을 과하게 높게 잡는 실수",
    tags: ["포트 오즈", "필요 승률"],
    pot: "50bb",
    villainBet: "10bb",
    actionBefore: "기존 팟 40bb에 상대가 10bb(1/4 팟) 베팅해 현재 팟이 50bb인 상황",
    mathFocus: "Quarter Pot Bet",
    options: [
      {
        value: "17",
        label: "약 17%",
      },
      {
        value: "25",
        label: "약 25%",
      },
      {
        value: "33",
        label: "약 33%",
      },
    ],
    correct: "17",
  },
  {
    id: "odds-016",
    category: "odds",
    difficulty: "기초",
    title: "One-Third Pot",
    prompt: "기존 팟 60bb에 상대가 20bb를 베팅했고, 1/3 팟 콜에 필요한 최소 승률을 바로 떠올려야 하는 상황입니다.",
    explanation: "1/3 팟 베팅엔 약 20%의 승률이 필요합니다. 하프 팟 25%와 함께 자주 나오는 기준이라 암기해 두면 좋습니다.",
    pitfall: "1/3 팟과 하프 팟의 필요 승률을 비슷하게 착각하는 실수",
    tags: ["포트 오즈", "필요 승률"],
    pot: "80bb",
    villainBet: "20bb",
    actionBefore: "기존 팟 60bb에 상대가 20bb(1/3 팟) 베팅해 현재 팟이 80bb인 상황",
    mathFocus: "One-Third Pot Bet",
    options: [
      {
        value: "17",
        label: "약 17%",
      },
      {
        value: "20",
        label: "약 20%",
      },
      {
        value: "25",
        label: "약 25%",
      },
    ],
    correct: "20",
  },
  {
    id: "odds-017",
    category: "odds",
    difficulty: "실전",
    title: "Two-Thirds Pot",
    prompt: "기존 팟 30bb에 상대가 20bb를 베팅해, 콜 금액 대비 최종 팟 크기를 계산해야 하는 상황입니다.",
    explanation: "2/3 팟 베팅엔 약 29%의 승률이 필요합니다. 팟 베팅 33%보다 조금 낮지만, 체감보다 꽤 높은 수치라서 콜이 줄어들어야 합니다.",
    pitfall: "2/3 팟 베팅 가격을 실제보다 싸게 느껴 너무 넓게 콜하는 실수",
    tags: ["포트 오즈", "필요 승률"],
    pot: "50bb",
    villainBet: "20bb",
    actionBefore: "기존 팟 30bb에 상대가 20bb(2/3 팟) 베팅해 현재 팟이 50bb인 상황",
    mathFocus: "Two-Thirds Pot Bet",
    options: [
      {
        value: "20",
        label: "약 20%",
      },
      {
        value: "29",
        label: "약 29%",
      },
      {
        value: "33",
        label: "약 33%",
      },
    ],
    correct: "29",
  },
  {
    id: "odds-018",
    category: "odds",
    difficulty: "실전",
    title: "Three-Quarter Pot",
    prompt: "기존 팟 40bb에 상대가 30bb를 베팅해, 하프팟보다 무거운 콜 가격이 걸려 있습니다.",
    explanation: "3/4 팟 베팅엔 약 30%의 승률이 필요합니다. 팟 베팅 직전 단계라서, 약한 드로우나 미약한 원페어는 점점 더 버리기 쉬워져야 합니다.",
    pitfall: "3/4 팟 베팅을 하프 팟 정도 가격으로 착각하는 실수",
    tags: ["포트 오즈", "필요 승률"],
    pot: "70bb",
    villainBet: "30bb",
    actionBefore: "기존 팟 40bb에 상대가 30bb(3/4 팟) 베팅해 현재 팟이 70bb인 상황",
    mathFocus: "Three-Quarter Pot Bet",
    options: [
      {
        value: "25",
        label: "약 25%",
      },
      {
        value: "30",
        label: "약 30%",
      },
      {
        value: "38",
        label: "약 38%",
      },
    ],
    correct: "30",
  },
  {
    id: "odds-019",
    category: "odds",
    difficulty: "응용",
    title: "1.5x Pot Overbet",
    prompt: "기존 팟 20bb에 상대가 30bb 오버벳을 했고, 평소보다 훨씬 비싼 콜의 필요 승률을 계산해야 합니다.",
    explanation: "1.5x 팟 오버벳엔 약 38%의 승률이 필요합니다. 생각보다 많이 이겨야 하므로, 이런 사이즈엔 콜 범위를 분명히 좁혀야 합니다.",
    pitfall: "오버벳의 높은 필요 승률을 무시하고 평소와 비슷하게 콜하는 실수",
    tags: ["포트 오즈", "필요 승률"],
    pot: "50bb",
    villainBet: "30bb",
    actionBefore: "기존 팟 20bb에 상대가 30bb(1.5x 팟) 베팅해 현재 팟이 50bb인 상황",
    mathFocus: "1.5x Pot Bet",
    options: [
      {
        value: "30",
        label: "약 30%",
      },
      {
        value: "38",
        label: "약 38%",
      },
      {
        value: "45",
        label: "약 45%",
      },
    ],
    correct: "38",
  },
  {
    id: "odds-020",
    category: "odds",
    difficulty: "응용",
    title: "2x Pot Overbet",
    prompt: "기존 팟 20bb에 상대가 40bb까지 밀어 넣어, 2배 팟 오버벳의 콜 가격을 숫자로 바로 판단해야 합니다.",
    explanation: "2x 팟 오버벳엔 약 40%의 승률이 필요합니다. 거의 절반 가까이 이겨야 하므로, 블러프 캐치 범위는 크게 줄어들어야 합니다.",
    pitfall: "2배 팟 오버벳에도 일반 베팅처럼 느슨하게 콜하는 실수",
    tags: ["포트 오즈", "필요 승률"],
    pot: "60bb",
    villainBet: "40bb",
    actionBefore: "기존 팟 20bb에 상대가 40bb(2x 팟) 베팅해 현재 팟이 60bb인 상황",
    mathFocus: "2x Pot Bet",
    options: [
      {
        value: "33",
        label: "약 33%",
      },
      {
        value: "40",
        label: "약 40%",
      },
      {
        value: "50",
        label: "약 50%",
      },
    ],
    correct: "40",
  },
  {
    id: "odds-021",
    category: "odds",
    difficulty: "기초",
    title: "Turn 5 Outs With Top Pair",
    prompt: "턴에서 JT로 탑페어를 들고 있고, 남은 T와 J가 리버에서 투페어나 트립스로 이어집니다.",
    explanation: "순수 아웃 계산 문제라 남은 T 3장으로 투페어, 남은 J 2장으로 트립스가 되어 총 5아웃으로 잡습니다. 턴 5아웃은 5/46으로 약 11%입니다.",
    pitfall: "이미 원페어를 들고 있다는 이유로 투페어·트립스로 좋아지는 아웃을 계산에서 빼먹는 실수",
    tags: ["아웃 계산", "턴 확률"],
    holeCards: ["Jh", "Tc"],
    board: ["Js", "8d", "5h", "2c"],
    outsSpec: {
      components: ["holePairImprove"],
    },
    pot: "24bb",
    villainBet: "16bb",
    actionBefore: "Turn: Top Pair can improve to Two Pair/Trips (5 Outs)",
    mathFocus: "5 Outs / Turn to River",
    options: [
      {
        value: "4",
        label: "약 4%",
      },
      {
        value: "11",
        label: "약 11%",
      },
      {
        value: "19",
        label: "약 19%",
      },
    ],
    correct: "11",
  },
  {
    id: "odds-022",
    category: "odds",
    difficulty: "기초",
    title: "Turn 10 Outs",
    prompt: "턴에서 AKo는 QJ72 보드에서, 리버 A나 K로 원페어를 만들거나 T로 브로드웨이 스트레이트를 완성할 수 있습니다.",
    explanation: "남은 A 3장, K 3장, T 4장으로 총 10아웃입니다. 턴 10아웃은 10/46으로 약 22%라서, 두 오버카드 6아웃으로만 줄여 잡으면 실제보다 너무 타이트하게 계산하게 됩니다.",
    pitfall: "브로드웨이를 완성하는 T 4장을 빼고 두 오버카드 6아웃으로만 계산하는 실수",
    tags: ["아웃 계산", "턴 확률"],
    holeCards: ["Ah", "Kd"],
    board: ["Qc", "Js", "7h", "2d"],
    outsSpec: {
      components: ["overcardPair", "straightDraw"],
    },
    pot: "20bb",
    villainBet: "12bb",
    actionBefore: "Turn: Two Overcards + Gutshot (10 Outs)",
    mathFocus: "10 Outs / Turn to River",
    options: [
      {
        value: "13",
        label: "약 13%",
      },
      {
        value: "22",
        label: "약 22%",
      },
      {
        value: "31",
        label: "약 31%",
      },
    ],
    correct: "22",
  },
  {
    id: "odds-023",
    category: "odds",
    difficulty: "실전",
    title: "Turn 12 Outs",
    prompt: "턴에서 AhJh는 KhTh5s2c 보드에서, 하트와 Q가 모두 개선 카드로 남아 있습니다.",
    explanation: "턴 12아웃은 약 26%입니다. 꽤 좋아 보이지만 여전히 4번 중 3번은 놓치므로, 가격과 사이즈를 꼭 함께 봐야 합니다.",
    pitfall: "강한 턴 드로우 12아웃을 무조건 콜 가능한 숫자로 착각하는 실수",
    tags: ["아웃 계산", "턴 확률"],
    holeCards: ["Ah", "Jh"],
    board: ["Kh", "Th", "5s", "2c"],
    outsSpec: {
      components: ["flushDraw", "straightDraw"],
    },
    pot: "28bb",
    villainBet: "18bb",
    actionBefore: "Turn: Flush Draw + Gutshot (12 Outs)",
    mathFocus: "12 Outs / Turn to River",
    options: [
      {
        value: "17",
        label: "약 17%",
      },
      {
        value: "26",
        label: "약 26%",
      },
      {
        value: "35",
        label: "약 35%",
      },
    ],
    correct: "26",
  },
  {
    id: "odds-024",
    category: "odds",
    difficulty: "실전",
    title: "Flop 10 Outs",
    prompt: "플랍에서 98은 T79 보드에서, 스트레이트와 트립스 쪽 개선을 함께 계산하는 상황입니다.",
    explanation: "플랍 10아웃은 약 38%입니다. 4분의 1보다 훨씬 높고, 절반보다는 낮은 중간대라는 감각을 익히는 것이 중요합니다.",
    pitfall: "10아웃 드로우를 막연히 50% 가까운 확률로 과대평가하는 실수",
    tags: ["아웃 계산", "플랍 확률"],
    holeCards: ["9h", "8c"],
    board: ["Th", "7d", "9d"],
    outsSpec: {
      components: ["straightDraw", "currentPairTrips"],
    },
    pot: "16bb",
    villainBet: "8bb",
    actionBefore: "Flop: OESD + Trips Draw (10 Outs)",
    mathFocus: "10 Outs / Flop to River",
    options: [
      {
        value: "24",
        label: "약 24%",
      },
      {
        value: "38",
        label: "약 38%",
      },
      {
        value: "54",
        label: "약 54%",
      },
    ],
    correct: "38",
  },
  {
    id: "odds-025",
    category: "odds",
    difficulty: "실전",
    title: "Flop 11 Outs",
    prompt: "플랍에서 KJ는 QT2 보드에서, 양방 스트레이트 가능성과 K로 원페어가 되는 경우가 함께 열려 있습니다.",
    explanation: "플랍 11아웃은 약 42%입니다. 절반에는 못 미치지만 상당히 높은 수치라, 가격이 좋다면 적극적으로 플레이할 이유가 생깁니다.",
    pitfall: "11아웃 드로우를 30%대 정도로 과소평가하는 실수",
    tags: ["아웃 계산", "플랍 확률"],
    holeCards: ["Kc", "Jc"],
    board: ["Qh", "Td", "2s"],
    outsSpec: {
      components: ["straightDraw", "overcardPair"],
    },
    pot: "18bb",
    villainBet: "9bb",
    actionBefore: "Flop: OESD + Overcard Pair (11 Outs)",
    mathFocus: "11 Outs / Flop to River",
    options: [
      {
        value: "31",
        label: "약 31%",
      },
      {
        value: "42",
        label: "약 42%",
      },
      {
        value: "54",
        label: "약 54%",
      },
    ],
    correct: "42",
  },
  {
    id: "odds-026",
    category: "odds",
    difficulty: "기초",
    title: "Turn 7 Outs",
    prompt: "턴에서 K9는 QJ52 보드에서, 거트샷과 K로 원페어가 되는 경우가 함께 남아 있습니다.",
    explanation: "턴 7아웃은 약 15%입니다. 8아웃 17%보다 조금 낮다고 생각하면 빠르게 실전에서 비교하기 좋습니다.",
    pitfall: "7아웃과 8아웃의 차이를 무시해 비슷한 확률로 처리하는 실수",
    tags: ["아웃 계산", "턴 확률"],
    holeCards: ["Kd", "9c"],
    board: ["Qs", "Jh", "5d", "2c"],
    outsSpec: {
      components: ["straightDraw", "overcardPair"],
    },
    pot: "26bb",
    villainBet: "14bb",
    actionBefore: "Turn: Gutshot + Overcard Pair (7 Outs)",
    mathFocus: "7 Outs / Turn to River",
    options: [
      {
        value: "9",
        label: "약 9%",
      },
      {
        value: "15",
        label: "약 15%",
      },
      {
        value: "24",
        label: "약 24%",
      },
    ],
    correct: "15",
  },
  {
    id: "odds-027",
    category: "odds",
    difficulty: "응용",
    title: "Flop 13 Outs",
    prompt: "플랍에서 JT는 Q9J 보드에서, 이미 페어를 갖고 있으면서 스트레이트 개선도 양쪽으로 열려 있습니다.",
    explanation: "플랍 13아웃은 약 48%입니다. 거의 반반에 가깝기 때문에, 강한 드로우가 왜 공격적으로 활용되는지 감을 잡는 데 좋습니다.",
    pitfall: "13아웃 큰 드로우의 실제 에퀴티를 절반보다 훨씬 낮게 보는 실수",
    tags: ["아웃 계산", "플랍 확률"],
    holeCards: ["Jd", "Tc"],
    board: ["Qh", "9s", "Jh"],
    outsSpec: {
      components: ["straightDraw", "holePairImprove"],
    },
    pot: "20bb",
    villainBet: "10bb",
    actionBefore: "Flop: OESD + Pair (13 Outs)",
    mathFocus: "13 Outs / Flop to River",
    options: [
      {
        value: "38",
        label: "약 38%",
      },
      {
        value: "48",
        label: "약 48%",
      },
      {
        value: "57",
        label: "약 57%",
      },
    ],
    correct: "48",
  },
  {
    id: "odds-028",
    category: "odds",
    difficulty: "응용",
    title: "Flop 15 Outs",
    prompt: "플랍에서 9h8h는 AhTd7h 보드에서, 플러시와 양방 스트레이트 개선이 함께 열려 있습니다.",
    explanation: "플랍 15아웃은 약 54%입니다. 절반을 넘는 강한 콤보 드로우라서, 프리미엄 원페어와도 충분히 맞설 수 있다는 감각을 익히기 좋습니다.",
    pitfall: "매우 강한 15아웃 콤보 드로우를 평범한 드로우 수준으로 과소평가하는 실수",
    tags: ["아웃 계산", "플랍 확률"],
    holeCards: ["9h", "8h"],
    board: ["Ah", "Td", "7h"],
    outsSpec: {
      components: ["flushDraw", "straightDraw"],
    },
    pot: "22bb",
    villainBet: "11bb",
    actionBefore: "Flop: Flush Draw + OESD (15 Outs)",
    mathFocus: "15 Outs / Flop to River",
    options: [
      {
        value: "45",
        label: "약 45%",
      },
      {
        value: "54",
        label: "약 54%",
      },
      {
        value: "67",
        label: "약 67%",
      },
    ],
    correct: "54",
  },
  {
    id: "odds-029",
    category: "odds",
    difficulty: "기초",
    title: "플랍 포켓페어 2아웃",
    prompt: "플랍에서 77은 AK2 보드에 맞지 않았고, 남은 두 장의 7이 떨어질 때만 셋으로 개선됩니다.",
    explanation: "플랍 2아웃은 약 8%입니다. 세트가 안 맞았을 때 얼마나 자주 그대로 끝나는지 체감하는 데 좋은 기준입니다.",
    pitfall: "포켓페어의 세트 확률을 실제보다 훨씬 높게 보는 실수",
    tags: ["아웃 계산", "플랍 확률"],
    holeCards: ["7c", "7d"],
    board: ["Ah", "Ks", "2c"],
    outsSpec: {
      components: ["pocketPairSet"],
    },
    pot: "12bb",
    villainBet: "6bb",
    actionBefore: "Flop: Pocket Pair to Set (2 Outs)",
    mathFocus: "2 Outs / Flop to River",
    options: [
      {
        value: "4",
        label: "약 4%",
      },
      {
        value: "8",
        label: "약 8%",
      },
      {
        value: "17",
        label: "약 17%",
      },
    ],
    correct: "8",
  },
  {
    id: "odds-030",
    category: "odds",
    difficulty: "기초",
    title: "턴 두 오버카드 6아웃",
    prompt: "턴에서 AK는 Q724 보드에 아직 페어가 없고, A나 K가 떨어질 때만 원페어로 개선됩니다.",
    explanation: "턴 6아웃은 약 13%입니다. 두 장 다 살아 있어 보여도 리버 한 장 기준으로는 생각보다 크지 않다는 감각이 중요합니다.",
    pitfall: "턴 두 오버카드를 막연히 20% 이상으로 과대평가하는 실수",
    tags: ["아웃 계산", "턴 확률"],
    holeCards: ["Ah", "Kc"],
    board: ["Qd", "7s", "2h", "4c"],
    outsSpec: {
      components: ["overcardPair"],
    },
    pot: "24bb",
    villainBet: "12bb",
    actionBefore: "Turn: 2 Overcards (6 Outs)",
    mathFocus: "6 Outs / Turn to River",
    options: [
      {
        value: "9",
        label: "약 9%",
      },
      {
        value: "13",
        label: "약 13%",
      },
      {
        value: "17",
        label: "약 17%",
      },
    ],
    correct: "13",
  },
  {
    id: "odds-031",
    category: "odds",
    difficulty: "실전",
    title: "턴 탑페어 2아웃",
    prompt: "턴에서 A9는 A72K 보드에 탑페어를 들고 있고, 남은 에이스 두 장이 떨어질 때만 트립스로 개선됩니다.",
    explanation: "턴 2아웃은 약 4%입니다. 이미 탑페어를 가졌더라도 리버 한 장으로 크게 좋아질 확률은 매우 낮다는 뜻입니다.",
    pitfall: "탑페어가 있으니 리버에서 자주 더 좋아질 거라고 막연히 기대하는 실수",
    tags: ["아웃 계산", "턴 확률"],
    holeCards: ["Ad", "9c"],
    board: ["As", "7h", "2d", "Kc"],
    outsSpec: {
      components: ["currentPairTrips"],
    },
    pot: "28bb",
    villainBet: "18bb",
    actionBefore: "Turn: Top Pair to Trips (2 Outs)",
    mathFocus: "2 Outs / Turn to River",
    options: [
      {
        value: "4",
        label: "약 4%",
      },
      {
        value: "9",
        label: "약 9%",
      },
      {
        value: "15",
        label: "약 15%",
      },
    ],
    correct: "4",
  },
  {
    id: "odds-032",
    category: "odds",
    difficulty: "실전",
    title: "턴 언더페어 2아웃",
    prompt: "턴까지 55는 Q92J 보드에서 아직 언더페어라, 남은 5 두 장이 떨어질 때만 셋으로 뒤집을 수 있습니다.",
    explanation: "턴 2아웃은 약 4%로 아주 낮습니다. 언더페어가 뒤집히는 장면만 기억하면 실제 확률을 자꾸 과대평가하게 됩니다.",
    pitfall: "턴 언더페어가 리버 한 장으로 자주 역전된다고 착각하는 실수",
    tags: ["아웃 계산", "턴 확률"],
    holeCards: ["5c", "5s"],
    board: ["Qh", "9d", "2c", "Jd"],
    outsSpec: {
      components: ["pocketPairSet"],
    },
    pot: "30bb",
    villainBet: "20bb",
    actionBefore: "Turn: Pocket Pair to Set (2 Outs)",
    mathFocus: "2 Outs / Turn to River",
    options: [
      {
        value: "4",
        label: "약 4%",
      },
      {
        value: "9",
        label: "약 9%",
      },
      {
        value: "17",
        label: "약 17%",
      },
    ],
    correct: "4",
  },
  {
    id: "odds-033",
    category: "odds",
    difficulty: "응용",
    title: "플랍 5아웃 페어 개선",
    prompt: "플랍에서 QJ는 KJ4 보드에서 이미 J 페어를 갖고 있고, Q나 J가 더 떨어지면 투페어나 트립스로 좋아집니다.",
    explanation: "플랍 5아웃은 약 20%입니다. 막연히 절반 가까이로 느끼기 쉬운 spot이지만, 실제론 다섯 번 중 한 번 정도입니다.",
    pitfall: "페어 개선 아웃을 감으로 크게 부풀려 판단하는 실수",
    tags: ["아웃 계산", "플랍 확률"],
    holeCards: ["Qd", "Js"],
    board: ["Kh", "Jc", "4s"],
    outsSpec: {
      components: ["holePairImprove"],
    },
    pot: "16bb",
    villainBet: "8bb",
    actionBefore: "Flop: Pair Improve (5 Outs)",
    mathFocus: "5 Outs / Flop to River",
    options: [
      {
        value: "11",
        label: "약 11%",
      },
      {
        value: "20",
        label: "약 20%",
      },
      {
        value: "31",
        label: "약 31%",
      },
    ],
    correct: "20",
  },
];
