import type { PostflopQuestion } from "../types";

export const postflopQuestions: PostflopQuestion[] = [
  {
    id: "post-001",
    category: "postflop",
    difficulty: "기초",
    title: "탑페어, 평범한 보드",
    prompt: "Q-high 레인보우 보드에서 탑페어를 맞췄고, 상대는 플랍에서 무난한 c-bet을 이어가고 있습니다.",
    explanation: "상대의 절반 팟 컨티뉴에이션 베팅에 QJ의 탑페어는 충분히 콜 가치가 있습니다. 이 보드에서 바로 레이즈하면 약한 블러프를 많이 접게 만듭니다.",
    pitfall: "탑페어를 잡자마자 과도하게 팟을 키우는 실수",
    tags: ["탑페어 운영", "플랍 콜다운"],
    position: "BB",
    preflopAction: "BTN 오픈, 나머지 폴드",
    holeCards: ["Qs", "Js"],
    board: ["Qh", "7d", "2s"],
    pot: "6.5bb",
    villainBet: "3bb",
    actionBefore: "BB 콜 vs BTN 오픈, 플랍 체크 후 BTN c-bet",
    stack: "97bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "topPair",
      boardTexture: "dry",
      suitTexture: "rainbow",
    },
    correct: "call",
  },
  {
    id: "post-002",
    category: "postflop",
    difficulty: "실전",
    title: "셋으로 체크레이즈 대응",
    prompt: "A-high 투톤 보드에서 셋을 만들었고, 체크레이즈까지 나와 드로우와 강한 메이드가 함께 얽혀 있습니다.",
    explanation: "A83 투톤에서 탑셋은 매우 강하지만, 같은 수트 드로우와 강한 Ax도 함께 얽힐 수 있습니다. 체크레이즈를 받더라도 드로우와 강한 에이스에서 크게 밸류를 받으면서 불편한 턴을 줄이기 위해 다시 레이즈가 좋습니다.",
    pitfall: "아주 강한 핸드로도 지나치게 느리게 플레이해 드로우에 공짜 카드를 주는 실수",
    tags: ["강한 메이드 핸드", "젖은 보드"],
    position: "CO",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Ah", "Ad"],
    board: ["As", "8s", "3d"],
    pot: "10bb",
    villainBet: "15bb 체크레이즈",
    actionBefore: "CO 오픈, BB 콜, 플랍에서 3bb c-bet 후 BB 체크레이즈",
    stack: "82bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "set",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-003",
    category: "postflop",
    difficulty: "기초",
    title: "거트샷만 있는 턴",
    prompt: "턴까지 왔는데 남은 개선 카드가 T 한 장뿐인 거트샷이고, 상대는 큰 사이즈로 압박하고 있습니다.",
    explanation: "거트샷 4아웃으로는 턴 대형 베팅을 따라갈 가격이 잘 나오지 않습니다. 라이브 초보가 가장 자주 하는 실수가 여기서 희망콜을 하는 것입니다.",
    pitfall: "거트샷만 보고 턴 큰 베팅을 계속 콜하는 실수",
    tags: ["약한 드로우", "턴 폴드"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Jh", "Th"],
    board: ["Ks", "9d", "3c", "2h"],
    pot: "18bb",
    villainBet: "14bb",
    actionBefore: "BTN 오픈에 BB 콜, 플랍 체크체크 후 턴에서 BB 리드",
    stack: "86bb 남음",
    reviewSpec: {
      street: "turn",
      draws: ["gutshot"],
      boardTexture: "dry",
      suitTexture: "rainbow",
    },
    correct: "fold",
  },
  {
    id: "post-004",
    category: "postflop",
    difficulty: "실전",
    title: "넛 플러시 드로우 + 오버카드",
    prompt: "플랍에서 A-high 넛 플러시 드로우에 오버카드까지 겹쳐 있어, 메이드 핸드는 없지만 개선 여지는 큽니다.",
    explanation: "넛 플러시 드로우와 에이스 오버카드는 충분한 에퀴티를 줍니다. 반 팟 정도 베팅에는 콜이 기본이며, 초보 기준으로 단순한 콜이 실수도 적습니다.",
    pitfall: "강한 드로우를 매번 즉시 레이즈해 과도한 변동성을 만드는 실수",
    tags: ["강한 드로우", "플랍 콜다운"],
    position: "BTN",
    preflopAction: "CO 오픈, 나머지 폴드",
    holeCards: ["Ah", "Jh"],
    board: ["Kh", "9h", "2c"],
    pot: "12bb",
    villainBet: "6bb",
    actionBefore: "CO 오픈에 BTN 콜, 플랍에서 CO c-bet",
    stack: "94bb 남음",
    reviewSpec: {
      street: "flop",
      draws: ["nutFlushDraw"],
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "call",
  },
  {
    id: "post-005",
    category: "postflop",
    difficulty: "실전",
    title: "투페어 vs 작은 돈크벳",
    prompt: "T87 투톤 보드에서 투페어를 만들었지만, 스트레이트와 플러시 쪽 연결이 많아 다음 스트리트가 편하지만은 않습니다. 상대는 작은 돈크벳으로 먼저 액션했습니다.",
    explanation: "T87 투톤에서 T7 투페어는 앞서 있는 경우가 많지만, 하트나 6, 9 같은 불편한 턴도 많이 열려 있습니다. 이런 소형 돈크벳에는 드로우와 원페어에게 더 내게 하면서 공짜 턴을 줄이기 위해 레이즈가 좋습니다.",
    pitfall: "강한 핸드인데도 젖은 보드에서 수동적으로 따라가기만 하는 실수",
    tags: ["강한 메이드 핸드", "젖은 보드"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Ts", "7s"],
    board: ["Td", "7h", "8h"],
    pot: "11bb",
    villainBet: "3bb",
    actionBefore: "BTN 오픈에 BB 콜, 플랍에서 BB 돈크벳",
    stack: "95bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "twoPair",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-006",
    category: "postflop",
    difficulty: "실전",
    title: "오버페어 vs 미니 체크레이즈",
    prompt: "낮은 드라이 보드에서 오버페어를 들고 있고, 상대의 미니 체크레이즈 범위는 아직 넓게 열려 있습니다.",
    explanation: "보드가 아주 젖지 않았고 상대의 미니 체크레이즈 범위엔 블러프와 약한 메이드가 섞일 수 있습니다. 일단 콜로 넓게 남겨두는 편이 좋습니다.",
    pitfall: "오버페어를 들고 플랍에서 무조건 스택을 넣으려는 실수",
    tags: ["오버페어 운영", "플랍 콜다운"],
    position: "HJ",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Kd", "Kc"],
    board: ["9s", "6d", "2c"],
    pot: "9bb",
    villainBet: "8bb 체크레이즈",
    actionBefore: "HJ 오픈, BB 콜, 플랍에서 3bb c-bet 후 BB 미니 체크레이즈",
    stack: "89bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "overpair",
      boardTexture: "dry",
      suitTexture: "rainbow",
    },
    correct: "call",
  },
  {
    id: "post-007",
    category: "postflop",
    difficulty: "응용",
    title: "멀티웨이 턴 오버벳",
    prompt: "멀티웨이로 턴까지 온 뒤 드로우가 막힌 보드에서 큰 오버벳을 받아, 원페어의 가치 판단이 까다롭습니다.",
    explanation: "드로우가 막힌 보드에서 오버벳은 세미블러프가 사라진 순수 밸류 범위입니다. 멀티웨이에서는 블러프 빈도가 헤즈업보다 훨씬 낮아 오버벳은 우리보다 강한 메이드 핸드 위주로 좁게 읽어야 합니다. 리레이즈하면 약한 핸드는 전부 접혀 우리가 이기는 범위만 날리고 강한 핸드만 남는 역선택이 생깁니다.",
    pitfall: "TPTK라서 절대 못 접겠다고 버티는 실수",
    tags: ["탑페어 운영", "멀티웨이"],
    position: "CO",
    preflopAction: "BTN 콜, BB 콜, 나머지 폴드",
    holeCards: ["Ac", "Qd"],
    board: ["Qh", "9c", "5s", "4d"],
    pot: "26bb",
    villainBet: "28bb",
    actionBefore: "CO 오픈, BTN 콜, BB 콜, 턴에서 BB 오버벳",
    stack: "78bb 남음",
    reviewSpec: {
      street: "turn",
      madeHand: "topPair",
      boardTexture: "dry",
      suitTexture: "rainbow",
    },
    correct: "fold",
  },
  {
    id: "post-008",
    category: "postflop",
    difficulty: "실전",
    title: "오픈엔디드 + 페어",
    prompt: "T87 보드에서 페어와 오픈엔디드가 함께 생겼고, 상대는 작은 c-bet으로 계속 압박하고 있습니다.",
    explanation: "98로 T87 보드라면 오픈엔디드 스트레이트 드로우와 페어를 동시에 가지고 있습니다. 작은 베팅에는 무난하게 콜이 좋습니다.",
    pitfall: "드로우 핸드를 매번 레이즈로만 해결하려는 실수",
    tags: ["강한 드로우", "플랍 콜다운"],
    position: "BB",
    preflopAction: "BTN 오픈, 나머지 폴드",
    holeCards: ["9s", "8s"],
    board: ["Td", "8c", "7h"],
    pot: "8bb",
    villainBet: "2.5bb",
    actionBefore: "BTN 오픈에 BB 콜, 플랍에서 BB 체크 후 BTN c-bet",
    stack: "96bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "middlePair",
      draws: ["oesd"],
      boardTexture: "wet",
      suitTexture: "rainbow",
    },
    correct: "call",
  },
  {
    id: "post-009",
    category: "postflop",
    difficulty: "실전",
    title: "리버 투페어 밸류벳",
    prompt: "리버에서 K와 9의 투페어가 완성됐고, 앞선 스트리트가 비교적 잔잔하게 지나간 뒤 상대가 체크했습니다.",
    explanation: "K9으로 K-high 보드에서 9가 리버에 떨어져 투페어가 완성된 상황입니다. 라이브 저스테이크에서 원페어 이상을 가진 상대가 콜해줄 가능성이 높으므로 반 팟 정도의 밸류벳이 좋습니다.",
    pitfall: "강한 완성 핸드를 체크백해서 리버 밸류를 놓치는 실수",
    tags: ["리버 밸류벳", "강한 메이드 핸드"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Kd", "9h"],
    board: ["Ks", "7c", "3d", "Jh", "9d"],
    pot: "22bb",
    villainBet: "체크",
    actionBefore: "BTN 오픈에 BB 콜, 플랍 체크콜, 턴 체크체크, 리버 체크",
    stack: "78bb 남음",
    reviewSpec: {
      street: "river",
      madeHand: "twoPair",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-010",
    category: "postflop",
    difficulty: "기초",
    title: "탑페어 vs 작은 c-bet",
    prompt: "Q-high 드라이 보드에서 탑페어를 맞췄고, 버튼의 작은 c-bet 앞에서 범위를 얼마나 넓게 두는지가 포인트입니다.",
    explanation: "AQ로 Q-high 보드에서 탑페어를 만들었다면 작은 c-bet에는 편하게 콜이 좋습니다. 레이즈부터 나가면 약한 블러프와 약한 Q를 너무 빨리 접게 만듭니다.",
    pitfall: "무난한 탑페어를 플랍에서 곧바로 과하게 키우는 실수",
    tags: ["탑페어 운영", "플랍 콜다운"],
    position: "BB",
    preflopAction: "BTN 오픈, 나머지 폴드",
    holeCards: ["As", "Qh"],
    board: ["Qd", "8c", "4s"],
    pot: "7.5bb",
    villainBet: "2.5bb",
    actionBefore: "BB 콜 vs BTN 오픈, 플랍 체크 후 BTN 소형 c-bet",
    stack: "97.5bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "topPair",
      boardTexture: "dry",
      suitTexture: "rainbow",
    },
    correct: "call",
  },
  {
    id: "post-011",
    category: "postflop",
    difficulty: "실전",
    title: "셋으로 플랍 재공격",
    prompt: "K-high 투톤 보드에서 셋을 만들었고, 체크레이즈가 나와 드로우와 메이드 핸드가 함께 얽혀 있습니다.",
    explanation: "K85 투톤에서 88 셋은 매우 강하지만, 체크레이즈 범위엔 강한 Kx와 각종 큰 드로우가 함께 들어올 수 있습니다. 다시 레이즈해 강한 메이드와 드로우에서 밸류를 받으면서 불편한 턴을 비싸게 만드는 쪽이 좋습니다.",
    pitfall: "젖은 보드에서 셋을 너무 느리게 플레이해 공짜 카드를 주는 실수",
    tags: ["강한 메이드 핸드", "젖은 보드"],
    position: "CO",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["8h", "8d"],
    board: ["Ks", "8s", "5c"],
    pot: "9bb",
    villainBet: "10bb 체크레이즈",
    actionBefore: "CO 오픈, BB 콜, 플랍 3bb c-bet 후 BB 체크레이즈",
    stack: "87bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "set",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-012",
    category: "postflop",
    difficulty: "기초",
    title: "턴 거트샷 정리",
    prompt: "턴까지 왔는데 KJ는 T 한 장만 필요한 거트샷이고, 상대의 두 번째 배팅 사이즈도 가볍지 않습니다.",
    explanation: "KJ로 Q93-2 보드면 스트레이트는 T 한 장뿐이라 4아웃 거트샷입니다. 큰 턴 배럴까지 따라가면 가격이 잘 맞지 않아 초보 기준으로는 폴드가 좋습니다.",
    pitfall: "턴에서 거트샷 하나만 보고 큰 배팅을 계속 따라가는 실수",
    tags: ["약한 드로우", "턴 폴드"],
    position: "BTN",
    preflopAction: "CO 오픈, 나머지 폴드",
    holeCards: ["Kd", "Jd"],
    board: ["Qc", "9s", "3h", "2c"],
    pot: "15bb",
    villainBet: "11bb",
    actionBefore: "BTN 콜 vs CO 오픈, 플랍 체크체크 후 턴에서 CO 배럴",
    stack: "89bb 남음",
    reviewSpec: {
      street: "turn",
      draws: ["gutshot"],
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "fold",
  },
  {
    id: "post-013",
    category: "postflop",
    difficulty: "응용",
    title: "콤보 드로우 세미블러프",
    prompt: "9h8c2h 플랍에서 오픈엔디드와 플러시 드로우가 함께 생겨, 메이드 없이도 에퀴티가 크게 걸린 상황입니다.",
    explanation: "JTh로 9h8c2h 플랍이면 오픈엔디드와 플러시 드로우가 겹친 콤보 드로우입니다. 작은 c-bet에는 레이즈로 폴드 에퀴티까지 챙기는 라인이 좋습니다.",
    pitfall: "매우 강한 드로우를 항상 수동적으로 콜만 하는 실수",
    tags: ["강한 드로우", "젖은 보드"],
    position: "BB",
    preflopAction: "BTN 오픈, 나머지 폴드",
    holeCards: ["Jh", "Th"],
    board: ["9h", "8c", "2h"],
    pot: "8bb",
    villainBet: "2.5bb",
    actionBefore: "BB 콜 vs BTN 오픈, 플랍 체크 후 BTN 소형 c-bet",
    stack: "96bb 남음",
    reviewSpec: {
      street: "flop",
      draws: ["flushDraw", "oesd", "comboDraw"],
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-014",
    category: "postflop",
    difficulty: "기초",
    title: "오버페어 vs 작은 돈크벳",
    prompt: "낮고 비교적 드라이한 보드에서 오버페어를 들고 있고, 상대는 작은 돈크벳으로 먼저 액션했습니다.",
    explanation: "QQ는 여전히 아주 앞선 핸드지만, 이런 작은 돈크벳엔 약한 페어나 블록 성격의 베팅도 많습니다. 바로 키우기보다 콜로 넓게 남겨두는 편이 좋습니다.",
    pitfall: "오버페어를 들고 작은 리드에 매번 즉시 큰 액션으로 대응하는 실수",
    tags: ["오버페어 운영", "플랍 콜다운"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Qc", "Qd"],
    board: ["9h", "5s", "2d"],
    pot: "8.5bb",
    villainBet: "2bb",
    actionBefore: "BTN 오픈에 BB 콜, 플랍에서 BB 소형 돈크벳",
    stack: "95bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "overpair",
      boardTexture: "dry",
      suitTexture: "rainbow",
    },
    correct: "call",
  },
  {
    id: "post-015",
    category: "postflop",
    difficulty: "실전",
    title: "투페어로 젖은 보드 압박",
    prompt: "Q98 보드에서 투페어를 만들었지만 스트레이트 쪽 연결도 많아, 강한 메이드 핸드라도 보드가 편하지는 않습니다.",
    explanation: "Q98에서 Q9 투페어는 앞서 있는 경우가 많지만, 스트레이트 연결이 많아 턴 카드가 자주 까다로워집니다. 작은 c-bet이나 리드에는 드로우와 한 페어 계열에서 값을 받으면서 공짜 카드를 막기 위해 레이즈가 좋습니다.",
    pitfall: "젖은 보드의 투페어를 콜만 하며 드로우에 쉬운 가격을 주는 실수",
    tags: ["강한 메이드 핸드", "젖은 보드"],
    position: "BB",
    preflopAction: "CO 오픈, 나머지 폴드",
    holeCards: ["Qh", "9h"],
    board: ["Qs", "9c", "8d"],
    pot: "8.5bb",
    villainBet: "3bb",
    actionBefore: "BB 콜 vs CO 오픈, 플랍 체크 후 CO c-bet",
    stack: "95bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "twoPair",
      boardTexture: "wet",
      suitTexture: "rainbow",
    },
    correct: "raise",
  },
  {
    id: "post-016",
    category: "postflop",
    difficulty: "응용",
    title: "멀티웨이 턴 큰 압박",
    prompt: "멀티웨이 턴에서 페어를 들고 있는데 큰 리드가 나와, 상대 범위를 보수적으로 봐야 하는 상황입니다.",
    explanation: "KJ로 J-high 보드에서 페어를 들고 있어도 멀티웨이 턴 오버사이즈 압박은 범위가 강합니다. 특히 초보 기준으로는 원페어 하나로 끝까지 버티기보다 과감히 접는 편이 손실이 적습니다.",
    pitfall: "멀티웨이 큰 턴 압박에도 페어면 무조건 버텨야 한다고 생각하는 실수",
    tags: ["탑페어 운영", "멀티웨이"],
    position: "CO",
    preflopAction: "BTN 콜, BB 콜, 나머지 폴드",
    holeCards: ["Kc", "Jc"],
    board: ["Jd", "8h", "4s", "Qd"],
    pot: "24bb",
    villainBet: "20bb",
    actionBefore: "CO 오픈, BTN 콜, BB 콜, 턴에서 BB 큰 리드",
    stack: "76bb 남음",
    reviewSpec: {
      street: "turn",
      madeHand: "middlePair",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "fold",
  },
  {
    id: "post-017",
    category: "postflop",
    difficulty: "실전",
    title: "리버 풀하우스 밸류",
    prompt: "리버에서 풀하우스를 완성했고, 상대가 먼저 체크했습니다.",
    explanation: "77로 7Q322 보드면 풀하우스라 거의 최상위 밸류 구간입니다. 라이브 저스테이크에서는 Qx 같은 강한 메이드도 생각보다 자주 콜하므로 작게라도 반드시 베팅하는 편이 좋습니다.",
    pitfall: "리버의 매우 강한 메이드 핸드를 체크백해 밸류를 흘리는 실수",
    tags: ["리버 밸류벳", "강한 메이드 핸드"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["7s", "7d"],
    board: ["7h", "Qc", "3s", "2d", "2c"],
    pot: "20bb",
    villainBet: "체크",
    actionBefore: "BTN 오픈에 BB 콜, 플랍 체크콜, 턴 체크체크, 리버 체크",
    stack: "80bb 남음",
    reviewSpec: {
      street: "river",
      madeHand: "fullHouse",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-018",
    category: "postflop",
    difficulty: "실전",
    title: "오픈엔디드 + 오버카드",
    prompt: "플랍에서 스트레이트 양방향 가능성과 두 장의 오버카드를 함께 들고 있어, 아직 메이드는 없지만 개선 카드가 많습니다.",
    explanation: "QJ로 T92 보드면 K나 8로 스트레이트가 완성되고, Q나 J가 떠도 어느 정도 쇼다운 가치가 생깁니다. 무난한 c-bet에는 콜이 기본입니다.",
    pitfall: "강한 개선 가능성이 있는 드로우를 너무 쉽게 접는 실수",
    tags: ["강한 드로우", "플랍 콜다운"],
    position: "BTN",
    preflopAction: "CO 오픈, 나머지 폴드",
    holeCards: ["Qc", "Jc"],
    board: ["Th", "9s", "2d"],
    pot: "8.5bb",
    villainBet: "3bb",
    actionBefore: "BTN 콜 vs CO 오픈, 플랍에서 CO c-bet",
    stack: "95bb 남음",
    reviewSpec: {
      street: "flop",
      draws: ["oesd"],
      boardTexture: "dry",
      suitTexture: "rainbow",
    },
    correct: "call",
  },
  {
    id: "post-019",
    category: "postflop",
    difficulty: "실전",
    title: "TPTK 턴 계속가기",
    prompt: "턴에서 탑페어 탑키커를 유지한 채 세컨드 배럴을 맞아, 강한 원페어를 어디까지 끌고 갈지 판단해야 합니다.",
    explanation: "AK로 에이스 보드에서 탑페어 탑키커는 강한 핸드지만, 레이즈하면 우리보다 약한 에이스(A2~A8)나 블러프는 전부 폴드하고 더 강한 메이드만 따라옵니다. 보드에 다이아 2장이 있어 상대가 다이아 드로우를 가질 수도 있지만, 플러시 아웃은 9장뿐이라 리버에서 완성 확률은 약 19%입니다. 지금은 콜로 약한 에이스와 블러프를 리버까지 끌고 가는 쪽이 기댓값이 높고, 리버에 세 번째 다이아가 깔리면 그때 베팅 크기에 맞게 재판단하면 됩니다.",
    pitfall: "TPTK에 자신감이 생겨 레이즈했다가 오히려 우리가 이기는 핸드만 다 접게 만드는 실수",
    tags: ["탑페어 운영", "플랍 콜다운"],
    position: "BB",
    preflopAction: "BTN 오픈, 나머지 폴드",
    holeCards: ["Ac", "Kc"],
    board: ["Ah", "7d", "4s", "Td"],
    pot: "16bb",
    villainBet: "11bb",
    actionBefore: "BB 콜 vs BTN 오픈, 플랍 체크콜 후 턴에서 BTN 세컨드 배럴",
    stack: "83bb 남음",
    reviewSpec: {
      street: "turn",
      madeHand: "topPair",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "call",
  },
  {
    id: "post-020",
    category: "postflop",
    difficulty: "실전",
    title: "턴 셋으로 크게 가져가기",
    prompt: "턴에서 셋이 완성됐고 보드에도 드로우가 남아 있어, 상대의 두 번째 배팅 뒤에 팟 크기 선택이 중요해집니다.",
    explanation: "66으로 J62T 보드에서 턴 셋이 완성되면 상대의 Jx, 큰 원페어, 클럽 드로우에서 아직 돈을 더 받을 수 있습니다. 콜만 하면 리버 액션이 죽기 쉬워, 지금 체크레이즈나 큰 레이즈로 밸류를 크게 챙기는 쪽이 좋습니다.",
    pitfall: "턴에서 강한 셋을 너무 느리게 플레이해 밸류를 놓치는 실수",
    tags: ["강한 메이드 핸드", "젖은 보드"],
    position: "BB",
    preflopAction: "CO 오픈, 나머지 폴드",
    holeCards: ["6h", "6d"],
    board: ["Jc", "6s", "2h", "Tc"],
    pot: "18bb",
    villainBet: "6bb",
    actionBefore: "BB 콜 vs CO 오픈, 턴에서 BB 체크 후 CO 세컨드 배럴",
    stack: "88bb 남음",
    reviewSpec: {
      street: "turn",
      madeHand: "set",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-021",
    category: "postflop",
    difficulty: "실전",
    title: "약해진 페어 vs 턴 더블배럴",
    prompt: "플랍에서는 페어로 버틸 수 있었지만, 턴 A와 큰 두 번째 배팅이 겹치며 상황이 한 단계 무거워졌습니다.",
    explanation: "98로 K94 보드에서 9를 맞췄어도, 턴 A가 뜬 뒤 큰 두 번째 배팅은 초보 기준으로 너무 무겁습니다. 상대의 밸류 구간에 자주 눌리므로 폴드가 좋습니다.",
    pitfall: "페어 하나로 턴 더블배럴까지 무리하게 콜다운하는 실수",
    tags: ["미들페어", "턴 더블배럴"],
    position: "BB",
    preflopAction: "BTN 오픈, 나머지 폴드",
    holeCards: ["9c", "8c"],
    board: ["Kd", "9h", "4s", "As"],
    pot: "15bb",
    villainBet: "11bb",
    actionBefore: "BB 콜 vs BTN 오픈, 플랍 체크콜 후 턴에서 BTN 큰 세컨드 배럴",
    stack: "85bb 남음",
    reviewSpec: {
      street: "turn",
      madeHand: "bottomPair",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "fold",
  },
  {
    id: "post-022",
    category: "postflop",
    difficulty: "실전",
    title: "드라이 보드 오버페어",
    prompt: "드로우가 거의 없는 보드에서 오버페어를 들고 있고, 상대의 작은 체크레이즈가 강한 밸류만 뜻하는지는 아직 불분명합니다.",
    explanation: "AA로 J64 레인보우 보드에서 작은 체크레이즈를 맞았다고 해도, 바로 3베팅으로 올릴 필요는 없습니다. 콜로 약한 Jx와 블러프를 남겨두는 편이 실전적입니다.",
    pitfall: "드라이 보드의 오버페어를 무조건 플랍에서 다 밀어 넣으려는 실수",
    tags: ["오버페어 운영", "드라이 보드"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Ah", "Ad"],
    board: ["Jc", "6h", "4d"],
    pot: "9bb",
    villainBet: "8bb 체크레이즈",
    actionBefore: "BTN 오픈에 BB 콜, 플랍 3bb c-bet 후 BB 미니 체크레이즈",
    stack: "89bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "overpair",
      boardTexture: "dry",
      suitTexture: "rainbow",
    },
    correct: "call",
  },
  {
    id: "post-023",
    category: "postflop",
    difficulty: "응용",
    title: "턴 콤보 드로우 공격",
    prompt: "턴에서 오픈엔디드와 플러시 드로우가 함께 생겨, 단순 콜과 압박 사이의 선택이 생긴 상황입니다.",
    explanation: "98s로 752-T 투톤 보드는 오픈엔디드와 플러시 드로우가 겹쳐 있습니다. 이런 유형은 레이즈로 폴드 에퀴티까지 챙기기 좋습니다.",
    pitfall: "턴의 매우 강한 콤보 드로우를 수동적으로 콜만 하는 실수",
    tags: ["강한 드로우", "젖은 보드"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["9s", "8s"],
    board: ["7d", "5s", "2s", "Tc"],
    pot: "16bb",
    villainBet: "10bb",
    actionBefore: "BTN 오픈에 BB 콜, 플랍 체크체크 후 턴에서 BB 리드",
    stack: "90bb 남음",
    reviewSpec: {
      street: "turn",
      draws: ["flushDraw", "oesd", "comboDraw"],
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-024",
    category: "postflop",
    difficulty: "실전",
    title: "리버 스트레이트 밸류",
    prompt: "리버에서 JT가 스트레이트를 완성했고, 체크를 받은 뒤 한 번 더 돈을 받을 수 있는지 판단해야 합니다.",
    explanation: "JT로 982Q 보드면 스트레이트가 완성됩니다. 라이브 저스테이크에선 강해 보이는 메이드도 체크콜하는 경우가 많아 베팅 가치가 충분합니다.",
    pitfall: "리버에서 완성 스트레이트를 체크백해 추가 밸류를 놓치는 실수",
    tags: ["리버 밸류벳", "강한 메이드 핸드"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Jc", "Tc"],
    board: ["9d", "8s", "2h", "Qd", "3c"],
    pot: "24bb",
    villainBet: "체크",
    actionBefore: "BTN 오픈에 BB 콜, 플랍 체크콜, 턴 체크체크, 리버 체크",
    stack: "76bb 남음",
    reviewSpec: {
      street: "river",
      madeHand: "straight",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-025",
    category: "postflop",
    difficulty: "실전",
    title: "낮은 셋, 젖은 보드",
    prompt: "854 투톤 보드에서 낮은 셋을 만들었고, 스트레이트와 플러시 쪽 드로우가 동시에 살아 있습니다.",
    explanation: "55로 854 투톤 보드에서 셋을 만들면 이미 매우 강한 핸드입니다. 스트레이트와 같은 수트 드로우가 많아 작은 돈크벳에는 레이즈로 드로우에게 더 내게 하면서 공짜 턴을 줄이는 쪽이 좋습니다.",
    pitfall: "젖은 보드의 낮은 셋을 지나치게 느리게 플레이하는 실수",
    tags: ["강한 메이드 핸드", "젖은 보드"],
    position: "CO",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["5c", "5s"],
    board: ["8d", "5h", "4h"],
    pot: "9bb",
    villainBet: "3bb",
    actionBefore: "CO 오픈에 BB 콜, 플랍에서 BB 돈크벳",
    stack: "95bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "set",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-026",
    category: "postflop",
    difficulty: "실전",
    title: "페어 + 넛 플러시 드로우",
    prompt: "Ad9d는 원페어와 넛 플러시 드로우가 함께 생긴 상황이라, 메이드 핸드와 드로우가 동시에 걸려 있습니다.",
    explanation: "Ad9d로 9h6d2d 보드를 맞으면 페어와 넛 플러시 드로우를 함께 갖게 됩니다. 표준 c-bet에는 충분히 콜할 수 있는 힘입니다.",
    pitfall: "페어와 강한 드로우가 겹친 손을 항상 즉시 레이즈로만 처리하는 실수",
    tags: ["강한 드로우", "플랍 콜다운"],
    position: "BTN",
    preflopAction: "CO 오픈, 나머지 폴드",
    holeCards: ["Ad", "9d"],
    board: ["9h", "6d", "2d"],
    pot: "8.5bb",
    villainBet: "3bb",
    actionBefore: "BTN 콜 vs CO 오픈, 플랍에서 CO c-bet",
    stack: "95bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "topPair",
      draws: ["nutFlushDraw"],
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "call",
  },
  {
    id: "post-027",
    category: "postflop",
    difficulty: "실전",
    title: "페어드 보드의 투페어",
    prompt: "턴에 보드가 페어되며 J와 7의 투페어가 완성됐고, 상대의 작은 리드가 밸류와 블러프를 함께 가질 수 있습니다.",
    explanation: "QJ로 J73-7 보드면 J와 7의 투페어가 되어 작은 턴 배팅엔 계속 콜할 수 있습니다. 여기서 성급하게 접으면 아직 앞선 경우를 너무 많이 놓치게 됩니다.",
    pitfall: "페어드 보드라고 해서 완성된 투페어까지 너무 쉽게 접는 실수",
    tags: ["강한 메이드 핸드", "드라이 보드"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Qd", "Jd"],
    board: ["Jc", "7s", "3h", "7d"],
    pot: "14bb",
    villainBet: "5bb",
    actionBefore: "BTN 오픈에 BB 콜, 플랍 체크콜 후 턴에서 BB 소형 리드",
    stack: "86bb 남음",
    reviewSpec: {
      street: "turn",
      madeHand: "twoPair",
      boardTexture: "dry",
      suitTexture: "rainbow",
    },
    correct: "call",
  },
  {
    id: "post-028",
    category: "postflop",
    difficulty: "응용",
    title: "턴 넛 플러시 드로우 + 거트샷",
    prompt: "턴에서 넛 플러시 드로우와 브로드웨이 거트샷이 겹쳐, 한 장만 남았어도 개선 카드 수가 적지 않습니다.",
    explanation: "AhQh로 JdTh4c2h 보드면 넛 플러시 드로우에 브로드웨이 거트샷까지 더해집니다. 한 장만 남았어도 개선 카드가 적지 않아 콜이 충분히 가능합니다.",
    pitfall: "턴의 강한 드로우를 겁먹고 필요 이상으로 쉽게 포기하는 실수",
    tags: ["강한 드로우", "턴 더블배럴"],
    position: "BTN",
    preflopAction: "CO 오픈, 나머지 폴드",
    holeCards: ["Ah", "Qh"],
    board: ["Jd", "Th", "4c", "2h"],
    pot: "18bb",
    villainBet: "10bb",
    actionBefore: "BTN 콜 vs CO 오픈, 플랍 체크콜 후 턴에서 CO 세컨드 배럴",
    stack: "82bb 남음",
    reviewSpec: {
      street: "turn",
      draws: ["nutFlushDraw", "gutshot", "comboDraw"],
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "call",
  },
  {
    id: "post-029",
    category: "postflop",
    difficulty: "실전",
    title: "리버 투페어 추가 밸류",
    prompt: "리버에서 A와 9의 투페어가 남았고, 상대가 체크해 얇은 밸류까지 받을 수 있는지 고민하게 됩니다.",
    explanation: "A9로 A9424 보드면 에이스와 9의 투페어를 들고 있습니다. 라이브 저스테이크에선 약한 Ax나 4x가 체크콜하는 경우가 있어 얇더라도 밸류를 챙겨야 합니다.",
    pitfall: "리버 투페어를 겁내서 체크백해 추가 밸류를 놓치는 실수",
    tags: ["리버 밸류벳", "강한 메이드 핸드"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Ac", "9c"],
    board: ["As", "9d", "4h", "4s", "2c"],
    pot: "22bb",
    villainBet: "체크",
    actionBefore: "BTN 오픈에 BB 콜, 플랍 체크콜, 턴 체크체크, 리버 체크",
    stack: "78bb 남음",
    reviewSpec: {
      street: "river",
      madeHand: "twoPair",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-030",
    category: "postflop",
    difficulty: "기초",
    title: "탑페어 vs 하프팟 c-bet",
    prompt: "K-high 레인보우 보드에서 탑페어를 맞췄고, 버튼의 하프팟 c-bet 앞에서 넓은 범위를 남길지가 포인트입니다.",
    explanation: "KJ로 K73 레인보우 보드에서 탑페어를 만들었다면 하프팟 c-bet엔 편하게 콜이 좋습니다. 여기서 곧바로 레이즈하면 약한 Kx와 블러프를 너무 빨리 접게 만듭니다.",
    pitfall: "무난한 탑페어를 플랍에서 바로 크게 키워 약한 범위를 몰아내는 실수",
    tags: ["탑페어 운영", "플랍 콜다운"],
    position: "BB",
    preflopAction: "BTN 오픈, 나머지 폴드",
    holeCards: ["Kd", "Jc"],
    board: ["Kh", "7s", "3d"],
    pot: "6.5bb",
    villainBet: "3.5bb",
    actionBefore: "BB 콜 vs BTN 오픈, 플랍 체크 후 BTN 하프팟 c-bet",
    stack: "96.5bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "topPair",
      boardTexture: "dry",
      suitTexture: "rainbow",
    },
    correct: "call",
  },
  {
    id: "post-031",
    category: "postflop",
    difficulty: "실전",
    title: "탑페어 + 오픈엔디드",
    prompt: "QJT 레인보우 보드에서 탑페어와 오픈엔디드가 함께 생겨, 메이드와 드로우가 같이 걸린 상황입니다.",
    explanation: "KQ로 QJT 보드를 맞으면 탑페어에 오픈엔디드까지 더해집니다. 작은 c-bet엔 콜로 계속 가며 상대의 블러프와 약한 밸류를 남겨 두는 편이 무난합니다.",
    pitfall: "탑페어와 오픈엔디드가 겹친 손을 무조건 크게 키우려는 실수",
    tags: ["탑페어 운영", "젖은 보드"],
    position: "BB",
    preflopAction: "CO 오픈, 나머지 폴드",
    holeCards: ["Kh", "Qh"],
    board: ["Qs", "Jd", "Tc"],
    pot: "7.5bb",
    villainBet: "2.5bb",
    actionBefore: "BB 콜 vs CO 오픈, 플랍 체크 후 CO 소형 c-bet",
    stack: "96bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "topPair",
      draws: ["oesd"],
      boardTexture: "wet",
      suitTexture: "rainbow",
    },
    correct: "call",
  },
  {
    id: "post-032",
    category: "postflop",
    difficulty: "기초",
    title: "미들페어 vs 작은 돈크벳",
    prompt: "K-high 드라이 보드에서 미들페어를 들고 있고, 빅블라인드의 작은 돈크벳이 넓은 범위로 나올 수 있습니다.",
    explanation: "QJ로 KJ4 보드면 미들페어라 아주 강하진 않지만 작은 돈크벳엔 충분히 계속 갈 수 있습니다. 바로 접어 버리면 약한 블러프와 얇은 프로브에 너무 많이 넘겨 주게 됩니다.",
    pitfall: "미들페어를 플랍 작은 리드 앞에서 지나치게 쉽게 접는 실수",
    tags: ["미들페어", "돈크벳 대응"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Qd", "Js"],
    board: ["Kh", "Jc", "4s"],
    pot: "9bb",
    villainBet: "2bb",
    actionBefore: "BTN 오픈에 BB 콜, 플랍에서 BB 소형 돈크벳",
    stack: "94bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "middlePair",
      boardTexture: "dry",
      suitTexture: "rainbow",
    },
    correct: "call",
  },
  {
    id: "post-033",
    category: "postflop",
    difficulty: "실전",
    title: "미들페어 + 플러시 드로우",
    prompt: "K-high 투톤 보드에서 미들페어와 플러시 드로우가 겹쳐, 쇼다운 가치와 개선 여지가 함께 있습니다.",
    explanation: "9h8h로 Kh9d4h 보드를 맞으면 미들페어에 플러시 드로우가 더해집니다. 무리한 레이즈보다 콜이 실수도 적고 약한 블러프를 남겨 두기 좋습니다.",
    pitfall: "미들페어와 플러시 드로우를 들고도 에퀴티를 과소평가해 너무 빨리 포기하는 실수",
    tags: ["미들페어", "젖은 보드"],
    position: "BB",
    preflopAction: "BTN 오픈, 나머지 폴드",
    holeCards: ["9h", "8h"],
    board: ["Kh", "9d", "4h"],
    pot: "8bb",
    villainBet: "2.5bb",
    actionBefore: "BB 콜 vs BTN 오픈, 플랍 체크 후 BTN 소형 c-bet",
    stack: "96bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "middlePair",
      draws: ["flushDraw"],
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "call",
  },
  {
    id: "post-034",
    category: "postflop",
    difficulty: "기초",
    title: "오버페어 vs 플랍 체크레이즈",
    prompt: "J-high 투톤 보드에서 오버페어를 들고 있는데, 체크레이즈 범위엔 강한 메이드와 드로우가 함께 섞일 수 있습니다.",
    explanation: "QQ로 J74 투톤 보드를 맞으면 여전히 강한 오버페어입니다. 플랍 체크레이즈를 받더라도 바로 3벳으로 잠그기보다 콜로 넓은 범위를 남겨 두는 편이 좋습니다.",
    pitfall: "오버페어를 들자마자 플랍 체크레이즈에 무조건 재공격하는 실수",
    tags: ["오버페어 운영", "체크레이즈"],
    position: "HJ",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Qc", "Qd"],
    board: ["Jc", "7c", "4h"],
    pot: "9bb",
    villainBet: "9bb 체크레이즈",
    actionBefore: "HJ 오픈에 BB 콜, 플랍 c-bet 후 BB 체크레이즈",
    stack: "88bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "overpair",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "call",
  },
  {
    id: "post-035",
    category: "postflop",
    difficulty: "실전",
    title: "투페어 vs 플랍 돈크벳",
    prompt: "Q96 투톤 보드에서 투페어를 만들었고, 빅블라인드의 작은 돈크벳 뒤로 불편한 턴이 적지 않습니다.",
    explanation: "Q9로 Q96 투톤 보드에서 투페어를 만들면 앞서 있는 경우가 많습니다. 작은 돈크벳엔 레이즈로 원페어와 드로우에게 더 내게 하면서 공짜 카드를 줄여야 합니다.",
    pitfall: "젖은 보드의 투페어를 수동적으로 콜만 해 다음 스트리트를 어렵게 만드는 실수",
    tags: ["강한 메이드 핸드", "돈크벳 대응"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Qd", "9d"],
    board: ["Qs", "9h", "6h"],
    pot: "10bb",
    villainBet: "3bb",
    actionBefore: "BTN 오픈에 BB 콜, 플랍에서 BB 소형 돈크벳",
    stack: "95bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "twoPair",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-036",
    category: "postflop",
    difficulty: "기초",
    title: "드라이 보드 셋 슬로우플레이",
    prompt: "A-high 레인보우 보드에서 셋을 만들었고, 상대의 작은 c-bet을 바로 키울지 한 번 더 남길지 판단해야 합니다.",
    explanation: "88로 A82 레인보우 보드에서 셋을 만들면 이미 매우 강합니다. 보드가 드라이하고 상대 c-bet도 작아 콜로 약한 Ax와 블러프를 남겨 두는 편이 좋습니다.",
    pitfall: "드라이 보드의 강한 셋을 늘 레이즈부터 해야 안심된다고 생각하는 실수",
    tags: ["셋 슬로우플레이", "드라이 보드"],
    position: "BB",
    preflopAction: "BTN 오픈, 나머지 폴드",
    holeCards: ["8c", "8d"],
    board: ["As", "8h", "2c"],
    pot: "7.5bb",
    villainBet: "2bb",
    actionBefore: "BB 콜 vs BTN 오픈, 플랍 체크 후 BTN 소형 c-bet",
    stack: "97bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "set",
      boardTexture: "dry",
      suitTexture: "rainbow",
    },
    correct: "call",
  },
  {
    id: "post-037",
    category: "postflop",
    difficulty: "응용",
    title: "플랍 트립스 즉시 밸류",
    prompt: "TTx 투톤 보드에서 트립스를 만들었고, 작은 c-bet 뒤로 드로우와 약한 메이드에게 더 받는 라인이 중요합니다.",
    explanation: "KT로 TT8 투톤 보드를 맞으면 트립스로 매우 앞서 있지만, 하트 드로우와 8x도 남아 있습니다. 작은 c-bet엔 레이즈로 바로 밸류를 챙기고 불편한 턴을 줄이는 쪽이 좋습니다.",
    pitfall: "플랍 트립스를 너무 느리게 플레이해 드로우에 공짜 턴을 주는 실수",
    tags: ["강한 메이드 핸드", "젖은 보드"],
    position: "BB",
    preflopAction: "BTN 오픈, 나머지 폴드",
    holeCards: ["Kd", "Tc"],
    board: ["Ts", "Th", "8h"],
    pot: "8bb",
    villainBet: "2.5bb",
    actionBefore: "BB 콜 vs BTN 오픈, 플랍 체크 후 BTN 소형 c-bet",
    stack: "95bb 남음",
    reviewSpec: {
      street: "flop",
      madeHand: "trips",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-038",
    category: "postflop",
    difficulty: "기초",
    title: "바텀페어 vs 턴 더블배럴",
    prompt: "턴에서 바텀페어만 남은 채 오버카드가 더 깔렸고, 상대는 두 번째 배럴로 계속 압박하고 있습니다.",
    explanation: "A5로 Q95K 보드는 플랍 바텀페어가 턴에서 더 약해진 전형적인 상황입니다. 두 번째 배럴까지 받으면 이길 수 있는 블러프 비중이 줄어 폴드가 좋습니다.",
    pitfall: "약해진 바텀페어를 이유 없이 끝까지 붙잡는 실수",
    tags: ["보텀페어", "턴 폴드"],
    position: "BTN",
    preflopAction: "CO 오픈, 나머지 폴드",
    holeCards: ["Ad", "5c"],
    board: ["Qh", "9s", "5d", "Kc"],
    pot: "16bb",
    villainBet: "11bb",
    actionBefore: "BTN 콜 vs CO 오픈, 플랍 콜 후 CO 턴 세컨드 배럴",
    stack: "83bb 남음",
    reviewSpec: {
      street: "turn",
      madeHand: "bottomPair",
      boardTexture: "wet",
      suitTexture: "rainbow",
    },
    correct: "fold",
  },
  {
    id: "post-039",
    category: "postflop",
    difficulty: "기초",
    title: "턴 오버페어 계속가기",
    prompt: "낮은 드라이 런아웃에서 오버페어를 유지하고 있고, 상대의 턴 배럴이 여전히 넓은 범위로 나올 수 있습니다.",
    explanation: "QQ로 J732 보드는 턴이 떨어져도 여전히 오버페어입니다. 과하게 겁먹고 접기보다 콜로 계속 가며 블러프와 Jx를 남겨 두는 편이 좋습니다.",
    pitfall: "턴까지 오버페어를 유지하고도 압박만 보고 지나치게 빨리 접는 실수",
    tags: ["오버페어 운영", "턴 더블배럴"],
    position: "BB",
    preflopAction: "CO 오픈, 나머지 폴드",
    holeCards: ["Qh", "Qc"],
    board: ["Jd", "7s", "3h", "2c"],
    pot: "14bb",
    villainBet: "9bb",
    actionBefore: "BB 콜 vs CO 오픈, 플랍 체크콜 후 CO 턴 세컨드 배럴",
    stack: "84bb 남음",
    reviewSpec: {
      street: "turn",
      madeHand: "overpair",
      boardTexture: "dry",
      suitTexture: "rainbow",
    },
    correct: "call",
  },
  {
    id: "post-040",
    category: "postflop",
    difficulty: "실전",
    title: "턴 투페어 vs 작은 리드",
    prompt: "턴에서 K와 Q의 투페어가 완성됐고, 빅블라인드의 작은 리드 뒤로 여전히 콜할 손이 적지 않습니다.",
    explanation: "KQ로 Q82-K 보드에서 투페어가 되면 작은 턴 리드엔 레이즈가 좋습니다. Qx와 다양한 세미블러프에게 더 내게 하면서 리버를 어렵지 않게 만들 수 있습니다.",
    pitfall: "턴에 강한 투페어가 됐는데도 작은 리드를 콜만 하고 넘기는 실수",
    tags: ["돈크벳 대응", "젖은 보드"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Kc", "Qd"],
    board: ["Qs", "8h", "2d", "Ks"],
    pot: "11bb",
    villainBet: "3bb",
    actionBefore: "BTN 오픈에 BB 콜, 플랍 체크체크 후 턴에서 BB 소형 리드",
    stack: "92bb 남음",
    reviewSpec: {
      street: "turn",
      madeHand: "twoPair",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-041",
    category: "postflop",
    difficulty: "실전",
    title: "턴 셋 체크레이즈",
    prompt: "턴에서 셋을 완성했고, 상대가 두 번째 배럴을 이어가며 아직 강한 원페어와 드로우를 갖고 있을 수 있습니다.",
    explanation: "99로 A42-9 보드에서 턴 셋이 되면 이제 크게 가져갈 시점입니다. 상대가 세컨드 배럴을 친 상황이라 체크레이즈로 밸류를 챙기고 리버 결정을 쉽게 만드는 편이 좋습니다.",
    pitfall: "턴에 셋을 맞추고도 지나치게 수동적으로 콜만 하는 실수",
    tags: ["강한 메이드 핸드", "체크레이즈"],
    position: "BB",
    preflopAction: "CO 오픈, 나머지 폴드",
    holeCards: ["9c", "9s"],
    board: ["Ah", "4c", "2d", "9d"],
    pot: "18bb",
    villainBet: "9bb",
    actionBefore: "BB 콜 vs CO 오픈, 플랍 체크콜 후 CO 턴 세컨드 배럴",
    stack: "82bb 남음",
    reviewSpec: {
      street: "turn",
      madeHand: "set",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-042",
    category: "postflop",
    difficulty: "실전",
    title: "턴 트립스 vs 멀티웨이 압박",
    prompt: "멀티웨이로 턴까지 온 뒤 트립스를 만들었지만, 큰 베팅이 나오면 더 강한 완성 핸드도 같이 봐야 합니다.",
    explanation: "A7로 K72-7 보드면 턴에 트립스를 만들지만, 멀티웨이 큰 배팅은 여전히 강한 값어치가 큽니다. 여기선 레이즈보다 콜로 Kx와 블러프를 남겨 두는 편이 안전합니다.",
    pitfall: "멀티웨이 큰 배팅 앞에서 트립스를 과신해 무조건 더 키우는 실수",
    tags: ["강한 메이드 핸드", "멀티웨이"],
    position: "CO",
    preflopAction: "BTN 콜, BB 콜, 나머지 폴드",
    holeCards: ["Ac", "7c"],
    board: ["Kh", "7s", "2d", "7d"],
    pot: "20bb",
    villainBet: "14bb",
    actionBefore: "CO 오픈, 플랍 체크체크 후 BTN이 턴 큰 배팅",
    stack: "86bb 남음",
    reviewSpec: {
      street: "turn",
      madeHand: "trips",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "call",
  },
  {
    id: "post-043",
    category: "postflop",
    difficulty: "기초",
    title: "리버 탑페어 블러프 캐치",
    prompt: "리버까지 드로우가 대부분 빗나간 보드에서 탑페어를 들고 있고, 상대는 큰 사이즈로 마지막 압박을 넣었습니다.",
    explanation: "AJ로 J7429 보드면 탑페어가 그대로 남아 있습니다. 큰 베팅이라도 미스드 드로우와 과한 압박이 섞일 수 있어 여기선 콜이 좋습니다.",
    pitfall: "리버에서 탑페어를 들고도 큰 베팅만 보고 자동 폴드하는 실수",
    tags: ["탑페어 운영", "리버 블러프 캐치"],
    position: "BB",
    preflopAction: "BTN 오픈, 나머지 폴드",
    holeCards: ["Ah", "Jc"],
    board: ["Jd", "7s", "4c", "2h", "9d"],
    pot: "24bb",
    villainBet: "16bb",
    actionBefore: "BB 콜 vs BTN 오픈, 플랍 체크콜, 턴 체크체크, 리버 큰 베팅",
    stack: "76bb 남음",
    reviewSpec: {
      street: "river",
      madeHand: "topPair",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "call",
  },
  {
    id: "post-044",
    category: "postflop",
    difficulty: "실전",
    title: "리버 투페어 밸류벳",
    prompt: "리버까지 무난하게 흘러온 뒤 K와 Q의 투페어가 그대로 남았고, 체크를 받으면 한 번 더 받는 쪽이 중요합니다.",
    explanation: "KQ로 KQ742 보드면 강한 투페어가 그대로 유지됩니다. 라이브 저스테이크에선 Kx와 Qx가 체크콜하는 경우가 있어 리버에서 밸류를 놓치지 말아야 합니다.",
    pitfall: "리버 투페어를 과하게 무서워해 체크백으로 끝내는 실수",
    tags: ["리버 밸류벳", "강한 메이드 핸드"],
    position: "BTN",
    preflopAction: "BB 콜, 나머지 폴드",
    holeCards: ["Kc", "Qd"],
    board: ["Ks", "Qh", "7d", "4c", "2s"],
    pot: "20bb",
    villainBet: "체크",
    actionBefore: "BTN 오픈에 BB 콜, 플랍 체크콜, 턴 체크체크, 리버 체크",
    stack: "80bb 남음",
    reviewSpec: {
      street: "river",
      madeHand: "twoPair",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "raise",
  },
  {
    id: "post-045",
    category: "postflop",
    difficulty: "응용",
    title: "리버 트립스 블러프 캐치",
    prompt: "리버에서 트립스를 만들었지만, 큰 베팅이 나오면 더 강한 완성 핸드 쪽 가치 베팅도 함께 의식하게 됩니다.",
    explanation: "A7로 K72Q7 보드면 리버에 트립스를 만들었습니다. 상대의 큰 리버 베팅엔 레이즈보다 콜로 약한 밸류와 블러프를 남겨 두는 편이 좋습니다.",
    pitfall: "리버 트립스를 맞추고도 보트만 떠올려 지나치게 쉽게 접는 실수",
    tags: ["리버 블러프 캐치", "강한 메이드 핸드"],
    position: "BB",
    preflopAction: "BTN 오픈, 나머지 폴드",
    holeCards: ["Ac", "7d"],
    board: ["Kh", "7s", "2c", "Qd", "7h"],
    pot: "24bb",
    villainBet: "15bb",
    actionBefore: "BB 콜 vs BTN 오픈, 플랍 체크콜, 턴 체크체크, 리버 큰 베팅",
    stack: "77bb 남음",
    reviewSpec: {
      street: "river",
      madeHand: "trips",
      boardTexture: "wet",
      suitTexture: "twoTone",
    },
    correct: "call",
  },
];
