import type { PreflopQuestion } from "../types";

export const preflopQuestions: PreflopQuestion[] = [
  {
    id: "pre-001",
    category: "preflop",
    difficulty: "기초",
    title: "UTG 첫 오픈 결정",
    prompt: "UTG에는 아직 액션하지 않은 플레이어가 많이 남아 있어, 오프수트 브로드웨이의 지배 문제가 크게 드러나기 쉽습니다.",
    explanation: "초반 포지션에서는 뒤에서 더 강한 A와 브로드웨이에 지배당하기 쉽습니다. 초보 기준으로는 접고 더 좋은 오픈을 기다리는 편이 안정적입니다.",
    pitfall: "오프수트 브로드웨이를 초반 포지션에서 과대평가하는 실수",
    tags: ["초반 포지션", "오프수트 브로드웨이"],
    hand: "AJo",
    holeCards: ["Ah", "Jc"],
    position: "UTG",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "모두 폴드",
    correct: "fold",
  },
  {
    id: "pre-002",
    category: "preflop",
    difficulty: "기초",
    title: "버튼 스틸 기회",
    prompt: "앞사람들이 모두 폴드해 버튼까지 왔고, 뒤에는 블라인드만 남아 있습니다. 76s는 포지션이 있을 때 포스트플랍 플레이성을 살리기 쉬운 핸드입니다.",
    explanation: "버튼에서 수딧 커넥터는 포지션 이점이 커서 오픈하기 좋습니다. 라이브 저스테이크에서는 블라인드가 많이 포기해 바로 팟을 가져가는 경우도 잦습니다.",
    pitfall: "플레이 가능 핸드를 너무 소극적으로 콜만 하거나 버리는 실수",
    tags: ["버튼 스틸", "수딧 커넥터"],
    hand: "76s",
    holeCards: ["7s", "6s"],
    position: "BTN",
    table: "120bb",
    stack: "유효스택 120bb",
    actionBefore: "모두 폴드",
    correct: "raise",
  },
  {
    id: "pre-003",
    category: "preflop",
    difficulty: "기초",
    title: "SB vs HJ 오픈",
    prompt: "스몰블라인드에서 HJ 오픈을 상대하면 포지션 없이 시작하고, KTo 같은 오프수트 브로드웨이는 이후 판단이 자주 꼬입니다.",
    explanation: "HJ 오픈에 대해 KTo는 지배당하기 쉽고, 스몰블라인드라서 이후에도 계속 불리합니다. 초보 기준으로는 과감히 폴드가 더 낫습니다.",
    pitfall: "스몰블라인드에서 너무 넓게 콜해 힘든 스팟을 만드는 실수",
    tags: ["SB 디펜스", "오프수트 브로드웨이"],
    hand: "KTo",
    holeCards: ["Kc", "Td"],
    position: "SB",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "HJ 3bb 오픈, 나머지 폴드",
    correct: "fold",
  },
  {
    id: "pre-004",
    category: "preflop",
    difficulty: "기초",
    title: "컷오프 밸류 오픈",
    prompt: "컷오프는 뒤 플레이어 수가 줄어드는 자리라, AQo 같은 강한 브로드웨이도 초반 포지션보다 부담이 덜합니다.",
    explanation: "여기서 콜은 상대 레이즈를 따라가는 게 아니라 BB에 1bb 림프로 들어가는 겁니다. 림프보다 레이즈가 팟을 더 크게 키우고 이니셔티브도 가져옵니다. AQo는 컷오프에서 오픈 레이즈가 기본입니다.",
    pitfall: "앞에 레이즈가 없는 스팟에서 콜(림프)로 들어가 팟도 못 키우고 이니셔티브도 잃는 실수",
    tags: ["컷오프 오픈", "강한 브로드웨이"],
    hand: "AQo",
    holeCards: ["Ac", "Qd"],
    position: "CO",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "모두 폴드",
    correct: "raise",
  },
  {
    id: "pre-005",
    category: "preflop",
    difficulty: "실전",
    title: "BB vs 버튼 민레이즈",
    prompt: "버튼 민레이즈를 받은 빅블라인드라 이미 투자된 칩이 있고, 작은 페어는 가격과 세트 잠재력을 함께 봐야 합니다.",
    explanation: "버튼 민레이즈에 55는 좋은 가격으로 콜할 수 있습니다. 지나치게 3베팅을 섞기보다 기본은 콜 쪽이 안정적입니다.",
    pitfall: "빅블라인드 방어 핸드를 필요 이상으로 공격적으로 바꾸는 실수",
    tags: ["BB 디펜스", "작은 페어"],
    hand: "55",
    holeCards: ["5c", "5d"],
    position: "BB",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "BTN 2bb 오픈, SB 폴드",
    correct: "call",
  },
  {
    id: "pre-006",
    category: "preflop",
    difficulty: "실전",
    title: "MP 수딧 에이스 오픈",
    prompt: "미들 포지션 선제 상황이라 뒤 플레이어는 남아 있지만, A5s는 수딧에 휠 가능성까지 있는 핸드입니다.",
    explanation: "미들 포지션에서 A5s는 플러시와 스트레이트 가능성이 있어 충분히 오픈 가능한 핸드입니다. 라이브 게임에서 블라인드 폴드도 자주 얻습니다.",
    pitfall: "수딧 에이스를 너무 타이트하게 접어 좋은 스팟을 놓치는 실수",
    tags: ["수딧 에이스", "미들 포지션"],
    hand: "A5s",
    holeCards: ["As", "5s"],
    position: "MP",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "모두 폴드",
    correct: "raise",
  },
  {
    id: "pre-007",
    category: "preflop",
    difficulty: "기초",
    title: "UTG 오프수트 브로드웨이",
    prompt: "초반 포지션에서는 뒤의 강한 브로드웨이와 에이스에 자주 부딪혀, 약한 오프수트 브로드웨이의 지배 문제가 크게 드러납니다.",
    explanation: "KJo는 KQ, AK, AJ 등에 자주 끌려다닙니다. 특히 라이브 풀링에서는 뒤에서 강한 콜 범위를 맞기 쉬워 초보 기준으로는 폴드가 편합니다.",
    pitfall: "KJ 계열을 초반 포지션에서 과신하는 실수",
    tags: ["초반 포지션", "지배당하는 핸드"],
    hand: "KJo",
    holeCards: ["Kd", "Jh"],
    position: "UTG",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "모두 폴드",
    correct: "fold",
  },
  {
    id: "pre-008",
    category: "preflop",
    difficulty: "실전",
    title: "버튼 아이솔레이트 스팟",
    prompt: "앞선 림프 둘 뒤의 버튼이라 포지션은 좋지만, 그냥 따라가면 블라인드까지 얽힌 멀티웨이가 되기 쉽습니다.",
    explanation: "포지션이 있고 A9o는 림퍼 상대로 충분한 우위를 가질 수 있습니다. 콜만 하면 블라인드까지 얽혀 어려운 멀티웨이가 됩니다.",
    pitfall: "좋은 아이솔레이트 기회를 콜로 흘려 보내는 실수",
    tags: ["버튼 스틸", "림퍼 아이솔레이트"],
    hand: "A9o",
    holeCards: ["Ah", "9c"],
    position: "BTN",
    table: "110bb",
    stack: "유효스택 110bb",
    actionBefore: "UTG 림프, HJ 림프, 나머지 폴드",
    correct: "raise",
  },
  {
    id: "pre-009",
    category: "preflop",
    difficulty: "실전",
    title: "BB 멀티웨이 디펜스",
    prompt: "오픈과 콜이 나온 뒤 빅블라인드라 가격은 좋아졌지만, 수딧 브로드웨이의 실현값과 멀티웨이 난이도를 함께 봐야 합니다.",
    explanation: "QJs는 플러시와 스트레이트 가능성이 있고, 이미 팟에 돈이 많이 들어가 콜 가격도 괜찮습니다. 과도한 3베팅보다는 콜이 무난합니다.",
    pitfall: "좋은 멀티웨이 핸드를 지나치게 공격적으로 바꾸거나 너무 쉽게 버리는 실수",
    tags: ["BB 디펜스", "수딧 브로드웨이"],
    hand: "QJs",
    holeCards: ["Qs", "Js"],
    position: "BB",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "CO 3bb 오픈, BTN 콜, SB 폴드",
    correct: "call",
  },
  {
    id: "pre-010",
    category: "preflop",
    difficulty: "실전",
    title: "SB 폴드 투 유",
    prompt: "폴드로 돌아온 스몰블라인드라 상대는 빅블라인드 한 명뿐이지만, 포지션 없이 시작하는 부담은 그대로 남아 있습니다.",
    explanation: "Q9s는 완벽한 프리미엄은 아니지만 헤즈업 포지션 불리함을 감수할 만큼 오픈 가치가 있습니다. 지나치게 타이트하면 블라인드를 너무 쉽게 넘겨줍니다.",
    pitfall: "폴드 투 유 스팟에서 스몰블라인드를 지나치게 타이트하게 운영하는 실수",
    tags: ["SB 스틸", "폴드 투 유"],
    hand: "Q9s",
    holeCards: ["Qh", "9h"],
    position: "SB",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "모두 폴드",
    correct: "raise",
  },
  {
    id: "pre-011",
    category: "preflop",
    difficulty: "실전",
    title: "HJ에서 TT vs CO 3벳",
    prompt: "하이잭에서 오픈한 뒤 컷오프 3벳을 받았고, TT는 강도는 있지만 오버카드가 뜨는 보드에서 자주 애매해집니다.",
    explanation: "TT는 좋은 핸드지만 3벳 팟에서 포지션 없이 플레이하면 오버카드가 뜰 때마다 어려워집니다. 라이브 저스테이크에서 3벳 범위는 보통 타이트하므로 콜해서 세트 마이닝하거나, 상대가 매우 루즈하지 않은 한 콜이 기본입니다.",
    pitfall: "미들 포켓페어로 3벳에 항상 4벳을 넣으려는 실수",
    tags: ["3벳 팟", "포켓페어 오픈"],
    hand: "TT",
    holeCards: ["Ts", "Td"],
    position: "HJ",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "HJ 3bb 오픈, CO 10bb 3벳",
    correct: "call",
  },
  {
    id: "pre-012",
    category: "preflop",
    difficulty: "기초",
    title: "HJ 수딧 브로드웨이 오픈",
    prompt: "하이잭은 아직 뒤 액션이 남아 있지만, KQs처럼 수딧 브로드웨이는 포스트플랍 연결성이 좋은 편입니다.",
    explanation: "KQs는 탑페어, 넛 계열 드로우, 스트레이트 가능성까지 있어 플레이성이 좋습니다. 초보 기준으로도 HJ에서 머뭇거릴 핸드는 아닙니다.",
    pitfall: "플레이성 좋은 수딧 브로드웨이를 미들 포지션에서 지나치게 소극적으로 접는 실수",
    tags: ["수딧 브로드웨이", "미들 포지션"],
    hand: "KQs",
    holeCards: ["Ks", "Qs"],
    position: "HJ",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "모두 폴드",
    correct: "raise",
  },
  {
    id: "pre-013",
    category: "preflop",
    difficulty: "기초",
    title: "CO 미들 페어 오픈",
    prompt: "컷오프는 뒤 플레이어 수가 적고, 88은 쇼다운 가치가 있으면서 세트 가능성도 남아 있습니다.",
    explanation: "88은 쇼다운 가치와 세트 잠재력이 모두 있어 컷오프 오픈이 자연스럽습니다. 콜만 기다리기보다 먼저 레이즈해 이니셔티브를 가져가는 편이 좋습니다.",
    pitfall: "포켓페어를 뒤에서 너무 자주 림프하거나 머뭇거리며 기회를 놓치는 실수",
    tags: ["포켓페어 오픈", "컷오프 오픈"],
    hand: "88",
    holeCards: ["8h", "8c"],
    position: "CO",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "모두 폴드",
    correct: "raise",
  },
  {
    id: "pre-014",
    category: "preflop",
    difficulty: "기초",
    title: "버튼 수딧 브로드웨이 스틸",
    prompt: "앞사람들이 모두 폴드해 버튼까지 왔고, KTs는 수딧이라 포스트플랍 연결도 살아 있는 브로드웨이 계열입니다.",
    explanation: "KTs는 포지션 이점과 플레이성이 좋아 버튼 스틸에 잘 맞습니다. 라이브 저스테이크에서는 블라인드가 바로 포기하는 빈도도 충분합니다.",
    pitfall: "버튼 스틸 구간에서 괜찮은 수딧 브로드웨이까지 과하게 포기하는 실수",
    tags: ["버튼 스틸", "수딧 브로드웨이"],
    hand: "KTs",
    holeCards: ["Kh", "Th"],
    position: "BTN",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "모두 폴드",
    correct: "raise",
  },
  {
    id: "pre-015",
    category: "preflop",
    difficulty: "기초",
    title: "SB 약한 오프수트 에이스 디펜스",
    prompt: "스몰블라인드에서 CO 오픈을 상대하면 포지션 없이 시작하고, A5o는 에이스가 있어도 킥커 문제가 자주 남습니다.",
    explanation: "A5o는 CO 오픈 범위에 지배당하기 쉽고, 스몰블라인드라서 이후에도 계속 불리합니다. 초보 기준으로는 수딧 버전이 아니라면 깔끔한 폴드가 편합니다.",
    pitfall: "에이스가 있다는 이유만으로 스몰블라인드에서 약한 오프수트 에이스를 계속 디펜스하는 실수",
    tags: ["SB 디펜스", "지배당하는 핸드"],
    hand: "A5o",
    holeCards: ["Ah", "5c"],
    position: "SB",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "CO 3bb 오픈, BTN 폴드",
    correct: "fold",
  },
  {
    id: "pre-016",
    category: "preflop",
    difficulty: "실전",
    title: "BB 수딧 에이스 방어",
    prompt: "버튼 민레이즈를 받은 빅블라인드라 가격이 나쁘지 않고, A4s는 수딧에 휠 백도어까지 있습니다.",
    explanation: "버튼 민레이즈 상대로 A4s는 플러시 가능성과 휠 백도어가 있어 콜 가치가 충분합니다. 초보 기준으로는 무리한 3벳보다 콜이 더 단순하고 안정적입니다.",
    pitfall: "빅블라인드 수딧 에이스를 무조건 폴드하거나 반대로 무조건 3벳으로만 처리하는 실수",
    tags: ["BB 디펜스", "수딧 에이스"],
    hand: "A4s",
    holeCards: ["As", "4s"],
    position: "BB",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "BTN 2bb 오픈, SB 폴드",
    correct: "call",
  },
  {
    id: "pre-017",
    category: "preflop",
    difficulty: "기초",
    title: "MP 99 선제 오픈",
    prompt: "미들 포지션 선제 상황이라 뒤 액션은 남아 있지만, 99는 쇼다운 가치가 있고 세트 가능성도 남아 있는 중간 페어입니다.",
    explanation: "99는 앞선 액션이 없을 때 충분히 오픈 가능한 강도입니다. 뒤에 남은 인원은 의식해야 하지만, 이런 핸드까지 접기 시작하면 범위가 너무 좁아집니다.",
    pitfall: "미들 포지션 포켓페어를 지나치게 타이트하게 접어 오픈 기회를 놓치는 실수",
    tags: ["포켓페어 오픈", "미들 포지션"],
    hand: "99",
    holeCards: ["9d", "9c"],
    position: "MP",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "모두 폴드",
    correct: "raise",
  },
  {
    id: "pre-018",
    category: "preflop",
    difficulty: "실전",
    title: "BTN에서 AJo vs UTG 오픈",
    prompt: "UTG 오픈은 대체로 강한 범위를 뜻하고, 버튼의 AJo는 포지션이 있어도 지배 문제에서 완전히 자유롭지 않습니다.",
    explanation: "AJo는 포지션이 있어도 UTG의 강한 레인지에 자주 눌립니다. 라이브 저스테이크에선 UTG 오픈이 더 타이트한 편이라 초보 기준으로는 폴드가 무난합니다.",
    pitfall: "버튼 포지션만 믿고 UTG 오픈에 지배당하는 오프수트 브로드웨이를 과신하는 실수",
    tags: ["오프수트 브로드웨이", "지배당하는 핸드"],
    hand: "AJo",
    holeCards: ["Ad", "Jh"],
    position: "BTN",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "UTG 3bb 오픈, MP/HJ/CO 폴드",
    correct: "fold",
  },
  {
    id: "pre-019",
    category: "preflop",
    difficulty: "실전",
    title: "CO 브로드웨이 아이솔레이트",
    prompt: "앞선 림프 하나 뒤의 컷오프라 포지션은 좋지만, 그냥 따라가면 버튼과 블라인드까지 멀티웨이에 섞이기 쉽습니다.",
    explanation: "컷오프의 KQo는 림퍼를 아이솔레이트하기 좋은 손입니다. 레이즈로 주도권을 잡아야 포지션 이점도 더 잘 살아납니다.",
    pitfall: "아이솔레이트가 좋은 브로드웨이를 콜로만 따라가 멀티웨이를 키우는 실수",
    tags: ["림퍼 아이솔레이트", "강한 브로드웨이"],
    hand: "KQo",
    holeCards: ["Kh", "Qc"],
    position: "CO",
    table: "110bb",
    stack: "유효스택 110bb",
    actionBefore: "UTG 림프, MP/HJ 폴드",
    correct: "raise",
  },
  {
    id: "pre-020",
    category: "preflop",
    difficulty: "실전",
    title: "BB 수딧 커넥터 디펜스",
    prompt: "버튼 오픈을 받은 빅블라인드라 가격을 일부 받았고, 76s는 연결성과 수딧 덕분에 포스트플랍 여지가 남습니다.",
    explanation: "76s는 포스트플랍에서 스트레이트와 플러시 가능성이 살아 있습니다. 버튼 오픈 상대로는 무리한 공격보다 콜로 실현값을 보는 편이 초보에게 좋습니다.",
    pitfall: "플레이성 좋은 수딧 커넥터를 빅블라인드에서 너무 쉽게 포기하는 실수",
    tags: ["BB 디펜스", "수딧 커넥터"],
    hand: "76s",
    holeCards: ["7h", "6h"],
    position: "BB",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "BTN 2.5bb 오픈, SB 폴드",
    correct: "call",
  },
  {
    id: "pre-021",
    category: "preflop",
    difficulty: "실전",
    title: "폴드 투 유 SB 스틸",
    prompt: "폴드로 돌아온 스몰블라인드라 상대는 빅블라인드 한 명뿐이지만, 헤즈업으로 포지션 없이 시작하는 자리입니다.",
    explanation: "J8s는 포지션 불리함이 있지만 헤즈업을 만들 가능성이 높아 오픈 가치가 있습니다. 지나치게 타이트하면 스몰블라인드에서 계속 손해를 봅니다.",
    pitfall: "폴드 투 유 상황에서도 스몰블라인드 오픈을 지나치게 좁게 잡는 실수",
    tags: ["SB 스틸", "폴드 투 유"],
    hand: "J8s",
    holeCards: ["Js", "8s"],
    position: "SB",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "모두 폴드",
    correct: "raise",
  },
  {
    id: "pre-022",
    category: "preflop",
    difficulty: "실전",
    title: "UTG 77 오픈 하한선",
    prompt: "UTG 선제 상황이라 뒤 액션은 많지만, 77은 즉시 쇼다운 가치와 세트 가능성을 함께 가진 포켓페어입니다.",
    explanation: "77은 UTG에서도 충분히 오픈 가능한 하한선 쪽 핸드입니다. 세트 잠재력과 즉시 쇼다운 가치를 모두 갖고 있어 먼저 레이즈하는 편이 낫습니다.",
    pitfall: "초반 포지션을 지나치게 의식해 오픈 가능한 포켓페어까지 접는 실수",
    tags: ["초반 포지션", "포켓페어 오픈"],
    hand: "77",
    holeCards: ["7d", "7c"],
    position: "UTG",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "모두 폴드",
    correct: "raise",
  },
  {
    id: "pre-023",
    category: "preflop",
    difficulty: "실전",
    title: "HJ ATo 오픈",
    prompt: "하이잭은 UTG보다 넓게 열 수 있지만 여전히 뒤 플레이어가 많아, ATo 같은 경계 핸드는 판단이 애매해지기 쉽습니다.",
    explanation: "ATo는 HJ에서 오픈 가능한 경계 핸드에 가깝고, 라이브 게임에선 선제 레이즈의 이점이 큽니다. 오프수트 브로드웨이라도 이 정도 강도면 먼저 여는 편이 좋습니다.",
    pitfall: "하이잭에서 오픈 가능한 오프수트 브로드웨이까지 지나치게 소극적으로 운영하는 실수",
    tags: ["오프수트 브로드웨이", "미들 포지션"],
    hand: "ATo",
    holeCards: ["Ah", "Td"],
    position: "HJ",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "모두 폴드",
    correct: "raise",
  },
  {
    id: "pre-024",
    category: "preflop",
    difficulty: "실전",
    title: "CO에서 JJ로 MP 오픈 대응",
    prompt: "미들 포지션 오픈을 받은 컷오프에서 JJ를 들고 있어, 포지션과 핸드 강도는 좋지만 뒤 플레이어 개입 가능성도 남아 있습니다.",
    explanation: "JJ는 MP 오픈에 맞서 밸류 3벳하기 좋은 손입니다. 콜만 하면 버튼과 블라인드까지 쉽게 얽히므로, 초보 기준으로도 선명하게 레이즈하는 편이 낫습니다.",
    pitfall: "강한 포켓페어를 항상 슬로우플레이해 멀티웨이를 허용하는 실수",
    tags: ["3벳 팟", "포켓페어 오픈"],
    hand: "JJ",
    holeCards: ["Jh", "Jc"],
    position: "CO",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "MP 3bb 오픈, HJ 폴드",
    correct: "raise",
  },
  {
    id: "pre-025",
    category: "preflop",
    difficulty: "실전",
    title: "BTN 수딧 브로드웨이 콜",
    prompt: "버튼에서 HJ 오픈을 상대하고 있고, KJs는 포지션과 플레이성을 함께 살릴 수 있는 수딧 브로드웨이입니다.",
    explanation: "KJs는 HJ 오픈에 대해 3벳만이 정답은 아닙니다. 라이브 저스테이크 초보 기준으로는 버튼에서 콜해 포지션 이점을 활용하는 라인이 충분히 좋습니다.",
    pitfall: "플레이성 좋은 버튼 콜 핸드를 무조건 3벳 아니면 폴드로만 생각하는 실수",
    tags: ["수딧 브로드웨이", "강한 브로드웨이"],
    hand: "KJs",
    holeCards: ["Ks", "Js"],
    position: "BTN",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "HJ 3bb 오픈, CO 폴드",
    correct: "call",
  },
  {
    id: "pre-026",
    category: "preflop",
    difficulty: "기초",
    title: "BB 작은 페어 방어",
    prompt: "컷오프 오픈을 받은 빅블라인드라 콜 비용이 줄어들고, 44는 작은 페어 특유의 세트 잠재력이 핵심입니다.",
    explanation: "44는 CO 오픈 상대로 바로 버리기엔 세트 가치가 충분합니다. 특히 이미 블라인드가 들어가 있어 콜 비용이 줄어드는 점도 중요합니다.",
    pitfall: "작은 페어의 세트 가치를 무시하고 빅블라인드에서 너무 쉽게 폴드하는 실수",
    tags: ["BB 디펜스", "작은 페어"],
    hand: "44",
    holeCards: ["4h", "4c"],
    position: "BB",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "CO 2.5bb 오픈, BTN/SB 폴드",
    correct: "call",
  },
  {
    id: "pre-027",
    category: "preflop",
    difficulty: "응용",
    title: "BTN에서 AQs vs UTG 오픈",
    prompt: "UTG 오픈을 받은 버튼이라 포지션 이점은 있지만, AQs는 핸드 강도와 상대 범위 존중을 함께 요구하는 손입니다.",
    explanation: "AQs는 강하지만 UTG 범위가 타이트해 무조건 3벳만 고집할 필요는 없습니다. 버튼에선 콜로도 충분히 좋은 실현값을 기대할 수 있습니다.",
    pitfall: "강한 수딧 브로드웨이를 상황 구분 없이 항상 3벳으로만 처리하는 실수",
    tags: ["수딧 브로드웨이", "강한 브로드웨이"],
    hand: "AQs",
    holeCards: ["As", "Qs"],
    position: "BTN",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "UTG 3bb 오픈, MP/HJ/CO 폴드",
    correct: "call",
  },
  {
    id: "pre-028",
    category: "preflop",
    difficulty: "실전",
    title: "CO 수딧 브로드웨이 아이솔레이트",
    prompt: "앞선 림프 하나 뒤의 컷오프에서 KJs를 들었고, 그냥 콜하면 버튼과 블라인드까지 팟에 쉽게 남을 수 있습니다.",
    explanation: "KJs는 컷오프에서 림퍼를 아이솔레이트하기 좋은 플레이성 있는 손입니다. 포지션과 주도권을 같이 챙기는 레이즈가 기본입니다.",
    pitfall: "수딧 브로드웨이 아이솔레이트 스팟을 콜로 흘려 보내는 실수",
    tags: ["림퍼 아이솔레이트", "수딧 브로드웨이"],
    hand: "KJs",
    holeCards: ["Kd", "Jd"],
    position: "CO",
    table: "120bb",
    stack: "유효스택 120bb",
    actionBefore: "UTG 림프, MP/HJ 폴드",
    correct: "raise",
  },
  {
    id: "pre-029",
    category: "preflop",
    difficulty: "실전",
    title: "BB에서 SB 림프 아이솔레이트",
    prompt: "스몰블라인드가 림프로 완성한 상황이라 빅블라인드는 공짜 플랍도 가능하지만, ATo처럼 우위가 있는 브로드웨이도 들고 있습니다.",
    explanation: "ATo는 SB 완성 범위를 상대로 앞서는 경우가 많아 레이즈 아이솔레이트가 좋습니다. 체크만 하면 포스트플랍에서 불필요하게 넓은 범위를 상대하게 됩니다.",
    pitfall: "스몰블라인드 림프를 빅블라인드에서 항상 공짜 플랍으로만 넘기는 실수",
    tags: ["림퍼 아이솔레이트", "BB 디펜스"],
    hand: "ATo",
    holeCards: ["Ac", "Td"],
    position: "BB",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "SB 1bb 완료",
    correct: "raise",
  },
  {
    id: "pre-030",
    category: "preflop",
    difficulty: "기초",
    title: "MP QJs 선제 오픈",
    prompt: "미들 포지션 선제 상황에서 QJs는 수딧과 연결성이 좋지만, 아직 뒤 플레이어들의 액션은 남아 있습니다.",
    explanation: "QJs는 탑페어, 스트레이트, 플러시 쪽으로 모두 잘 이어지는 핸드입니다. 이런 손까지 접으면 미들 포지션 범위가 지나치게 약해집니다.",
    pitfall: "플레이성 좋은 수딧 브로드웨이를 미들 포지션에서 과도하게 타이트하게 접는 실수",
    tags: ["수딧 브로드웨이", "미들 포지션"],
    hand: "QJs",
    holeCards: ["Qh", "Jh"],
    position: "MP",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "모두 폴드",
    correct: "raise",
  },
  {
    id: "pre-031",
    category: "preflop",
    difficulty: "응용",
    title: "HJ에서 QQ로 UTG 오픈 대응",
    prompt: "UTG 오픈을 받은 하이잭에서 QQ를 들고 있어 핸드 강도는 높지만, 콜만 하면 뒤 플레이어가 합류할 여지도 있습니다.",
    explanation: "QQ는 UTG 오픈 범위 상대로도 충분한 밸류가 있습니다. 하이잭에서 콜만 하면 뒤 플레이어를 끌어들이기 쉬우므로 3벳으로 팟 주도권을 잡아야 합니다.",
    pitfall: "아주 강한 포켓페어를 지나치게 조심스럽게 콜만 해 멀티웨이를 허용하는 실수",
    tags: ["3벳 팟", "포켓페어 오픈"],
    hand: "QQ",
    holeCards: ["Qd", "Qc"],
    position: "HJ",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "UTG 3bb 오픈, MP 폴드",
    correct: "raise",
  },
  {
    id: "pre-032",
    category: "preflop",
    difficulty: "기초",
    title: "CO 77 선제 오픈",
    prompt: "컷오프 선제 상황에서 77은 뒤 액션이 남아 있지만, 쇼다운 가치와 세트 잠재력을 함께 가진 손입니다.",
    explanation: "77은 컷오프 first-in이면 무난한 오픈입니다. 이런 중간 포켓페어를 계속 접어 버리면 라이브 오픈 범위가 지나치게 좁아집니다.",
    pitfall: "오픈 기회가 왔는데 중간 포켓페어를 지나치게 소극적으로 넘기는 실수",
    tags: ["포켓페어 오픈", "컷오프 오픈"],
    hand: "77",
    holeCards: ["7h", "7c"],
    position: "CO",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "UTG/MP/HJ 폴드",
    correct: "raise",
  },
  {
    id: "pre-033",
    category: "preflop",
    difficulty: "실전",
    title: "BTN AJo 림퍼 아이솔레이트",
    prompt: "하이잭 림프 뒤의 버튼에서 AJo를 들었고, 콜만 하면 블라인드까지 쉽게 팟에 남을 수 있습니다.",
    explanation: "AJo는 림퍼 하나를 상대로 아이솔레이트하기 충분한 손입니다. 포지션과 주도권을 같이 가져오는 레이즈가 라이브 저스테이크에서 특히 중요합니다.",
    pitfall: "우위가 있는 오프수트 브로드웨이로 림퍼를 그냥 따라만 가는 실수",
    tags: ["림퍼 아이솔레이트", "오프수트 브로드웨이"],
    hand: "AJo",
    holeCards: ["Ah", "Jc"],
    position: "BTN",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "HJ 림프, CO 폴드",
    correct: "raise",
  },
  {
    id: "pre-034",
    category: "preflop",
    difficulty: "응용",
    title: "SB KQs vs CO 오픈",
    prompt: "컷오프 오픈을 받은 스몰블라인드라 불리한 자리지만, KQs는 핸드 강도와 플레이성을 함께 갖춘 브로드웨이입니다.",
    explanation: "KQs는 CO 오픈 상대로 너무 강해서 바로 접기 아깝고, 3벳만 고집할 필요도 없습니다. 스몰블라인드에선 콜로 계속 가며 플랍 이후 실현값을 노리는 쪽이 무난합니다.",
    pitfall: "강한 수딧 브로드웨이를 선행 오픈 앞에서 지나치게 단순하게 3벳이나 폴드로만 처리하는 실수",
    tags: ["SB 디펜스", "수딧 브로드웨이"],
    hand: "KQs",
    holeCards: ["Ks", "Qs"],
    position: "SB",
    table: "100bb",
    stack: "유효스택 100bb",
    actionBefore: "CO 2.5bb 오픈, BTN 폴드",
    correct: "call",
  },
];
